-- AlterTable
ALTER TABLE `historical_country` ADD COLUMN `entity_kind` ENUM('STATE', 'REGIME', 'PERIOD') NULL,
    MODIFY `state_type` ENUM('EMPIRE', 'KINGDOM', 'PRINCIPALITY', 'ELECTORATE', 'MARGRAVIATE', 'REPUBLIC', 'FEDERATION', 'CONFEDERATION', 'CITY_STATE', 'CALIPHATE', 'SULTANATE', 'KHANATE', 'THEOCRACY', 'TRIBAL_STATE', 'NOMADIC_EMPIRE', 'DYNASTY', 'HEREDITARY', 'SHOGUNATE', 'PERSONAL_UNION', 'OTHER') NOT NULL;

-- AlterTable
ALTER TABLE `historical_country_transition` ADD COLUMN `transition_scope` ENUM('STATE_SUCCESSION', 'REGIME_CHANGE') NULL;