/**
 * @packageDocumentation
 * @module api.functional.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { LoginDto } from "../../../libs/auth/presentation/dto/login.dto";
import type { LoginResponseDto } from "../../../libs/auth/presentation/dto/login.response";

/**
 * 로그인 요청 처리
 *
 * @param dto - 로그인 요청 데이터
 * @returns - 로그인 응답 데이터
 *
 * @controller AuthController.login
 * @path POST /auth/login
 * @accessor api.functional.auth.login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  dto: login.Body,
): Promise<login.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...login.METADATA,
      template: login.METADATA.path,
      path: login.path(),
    },
    dto,
  );
}
export namespace login {
  export type Body = Primitive<LoginDto>;
  export type Output = Primitive<LoginResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/auth/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/login";
}

/**
 * @controller AuthController.session
 * @path GET /auth/session
 * @accessor api.functional.auth.session
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function session(
  connection: IConnection,
): Promise<session.Output> {
  return PlainFetcher.fetch(connection, {
    ...session.METADATA,
    template: session.METADATA.path,
    path: session.path(),
  });
}
export namespace session {
  export type Output = Primitive<{
    hasAccessCookie: boolean;
    hasRefreshCookie: boolean;
    accessValid: boolean;
  }>;

  export const METADATA = {
    method: "GET",
    path: "/auth/session",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/session";
}

/**
 * @controller AuthController.refresh
 * @path POST /auth/refresh
 * @accessor api.functional.auth.refresh
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function refresh(
  connection: IConnection,
): Promise<refresh.Output> {
  return PlainFetcher.fetch(connection, {
    ...refresh.METADATA,
    template: refresh.METADATA.path,
    path: refresh.path(),
  });
}
export namespace refresh {
  export type Output = Primitive<{ ok: boolean }>;

  export const METADATA = {
    method: "POST",
    path: "/auth/refresh",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/refresh";
}
