-- AlterTable
ALTER TABLE `attachment` MODIFY `owner_type` ENUM('CONTINENT_RECORD', 'COUNTRY', 'PERSON', 'RESOURCE', 'ADMINISTRATIVE_DIVISION', 'ADMINISTRATION_DEPARTMENT', 'ADMINISTRATION_DEPARTMENT_EVENT', 'DYNASTY') NOT NULL,
    MODIFY `file_path` VARCHAR(500) NOT NULL;

-- AlterTable
ALTER TABLE `dynasty` DROP COLUMN `thumbnail_url`;