/**
 * @packageDocumentation
 * @module api.functional.users.by_name
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { UserResponseDto } from "../../../../libs/user/presentation/dto/user-response.dto";

/**
 * 사용자 조회 (displayName)
 * @controller UserController.findByDisplayName
 * @path GET /users/by-name/:displayName
 * @accessor api.functional.users.by_name.findByDisplayName
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findByDisplayName(
  connection: IConnection,
  displayName: string,
): Promise<findByDisplayName.Output> {
  return PlainFetcher.fetch(connection, {
    ...findByDisplayName.METADATA,
    template: findByDisplayName.METADATA.path,
    path: findByDisplayName.path(displayName),
  });
}
export namespace findByDisplayName {
  export type Output = Primitive<UserResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/users/by-name/:displayName",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (displayName: string) =>
    `/users/by-name/${encodeURIComponent(displayName?.toString() ?? "null")}`;
}
