-- AlterTable
ALTER TABLE `company_history` MODIFY `type` ENUM('GENERAL', 'PRODUCT_LAUNCH', 'FINANCIAL', 'MERGER_ACQUISITION', 'LEADERSHIP', 'LEGAL', 'MILESTONE', 'OTHER', 'CAPITAL_INVESTMENT', 'PARTNERSHIP', 'CAPITAL_POLICY', 'RESTRUCTURING', 'REGULATORY', 'INCIDENT') NULL DEFAULT 'GENERAL';
