/**
 * @packageDocumentation
 * @module api.functional.account
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { AccountMeResponseDto } from "../../../libs/auth/presentation/dto/account-me.response";

export * as change_password from "./change_password/index";
export * as display_name from "./display_name/index";
export * as representative_person from "./representative_person/index";

/**
 * @controller AccountController.me
 * @path GET /account/me
 * @accessor api.functional.account.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function me(connection: IConnection): Promise<me.Output> {
  return PlainFetcher.fetch(connection, {
    ...me.METADATA,
    template: me.METADATA.path,
    path: me.path(),
  });
}
export namespace me {
  export type Output = Primitive<AccountMeResponseDto | null>;

  export const METADATA = {
    method: "GET",
    path: "/account/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/account/me";
}
