/**
 * @packageDocumentation
 * @module api.functional.historical_countries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { CreateHistoricalCountryDto } from "../../../libs/historical-country/presentation/dto/create-historical-country.dto";
import type { HistoricalCountryResponseDto } from "../../../libs/historical-country/presentation/dto/historical-country.response";
import type { UpdateHistoricalCountryDto } from "../../../libs/historical-country/presentation/dto/update-historical-country.dto";

export * as by_ids from "./by_ids/index";
export * as transitions from "./transitions/index";
export * as memberships from "./memberships/index";
export * as relations from "./relations/index";

/**
 * 역사적 국가 목록 조회 (본인 등록분만).
 * 쿼리: entityKind (STATE|REGIME|PERIOD), stateType (예: SHOGUNATE) 로 필터 가능.
 *
 * @returns 역사적 국가 목록
 * @tag historical-countries
 *
 * @controller HistoricalCountryController.getAllHistoricalCountries
 * @path GET /historical-countries
 * @accessor api.functional.historical_countries.getAllHistoricalCountries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllHistoricalCountries(
  connection: IConnection,
  entityKind?: string,
  stateType?: string,
): Promise<getAllHistoricalCountries.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAllHistoricalCountries.METADATA,
    template: getAllHistoricalCountries.METADATA.path,
    path: getAllHistoricalCountries.path(entityKind, stateType),
  });
}
export namespace getAllHistoricalCountries {
  export type Output = Primitive<Array<HistoricalCountryResponseDto>>;

  export const METADATA = {
    method: "GET",
    path: "/historical-countries",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (entityKind?: string, stateType?: string) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      entityKind: entityKind,
      stateType: stateType,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/historical-countries";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * 역사적 국가 상세 조회 (본인 등록분만)
 *
 * @param id 역사적 국가 ID
 * @returns 역사적 국가 정보
 * @tag historical-countries
 *
 * @controller HistoricalCountryController.getHistoricalCountryById
 * @path GET /historical-countries/:id
 * @accessor api.functional.historical_countries.getHistoricalCountryById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHistoricalCountryById(
  connection: IConnection,
  id: string,
): Promise<getHistoricalCountryById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getHistoricalCountryById.METADATA,
    template: getHistoricalCountryById.METADATA.path,
    path: getHistoricalCountryById.path(id),
  });
}
export namespace getHistoricalCountryById {
  export type Output = Primitive<HistoricalCountryResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/historical-countries/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/historical-countries/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 역사적 국가 생성 (현재 계정 소유로 등록)
 *
 * @param dto 역사적 국가 생성 정보
 * @returns 생성된 역사적 국가
 * @tag historical-countries
 *
 * @controller HistoricalCountryController.createHistoricalCountry
 * @path POST /historical-countries
 * @accessor api.functional.historical_countries.createHistoricalCountry
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createHistoricalCountry(
  connection: IConnection,
  dto: createHistoricalCountry.Body,
): Promise<createHistoricalCountry.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createHistoricalCountry.METADATA,
      template: createHistoricalCountry.METADATA.path,
      path: createHistoricalCountry.path(),
    },
    dto,
  );
}
export namespace createHistoricalCountry {
  export type Body = Primitive<CreateHistoricalCountryDto>;
  export type Output = Primitive<HistoricalCountryResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/historical-countries",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/historical-countries";
}

/**
 * 역사적 국가 수정
 *
 * @param id 역사적 국가 ID
 * @param dto 역사적 국가 수정 정보
 * @returns 수정된 역사적 국가
 * @tag historical-countries
 *
 * @controller HistoricalCountryController.updateHistoricalCountry
 * @path PUT /historical-countries/:id
 * @accessor api.functional.historical_countries.updateHistoricalCountry
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateHistoricalCountry(
  connection: IConnection,
  id: string,
  dto: updateHistoricalCountry.Body,
): Promise<updateHistoricalCountry.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateHistoricalCountry.METADATA,
      template: updateHistoricalCountry.METADATA.path,
      path: updateHistoricalCountry.path(id),
    },
    dto,
  );
}
export namespace updateHistoricalCountry {
  export type Body = Primitive<UpdateHistoricalCountryDto>;
  export type Output = Primitive<HistoricalCountryResponseDto>;

  export const METADATA = {
    method: "PUT",
    path: "/historical-countries/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/historical-countries/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 역사적 국가 삭제
 *
 * @param id 역사적 국가 ID
 * @tag historical-countries
 *
 * @controller HistoricalCountryController.deleteHistoricalCountry
 * @path DELETE /historical-countries/:id
 * @accessor api.functional.historical_countries.deleteHistoricalCountry
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteHistoricalCountry(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteHistoricalCountry.METADATA,
    template: deleteHistoricalCountry.METADATA.path,
    path: deleteHistoricalCountry.path(id),
  });
}
export namespace deleteHistoricalCountry {
  export const METADATA = {
    method: "DELETE",
    path: "/historical-countries/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string) =>
    `/historical-countries/${encodeURIComponent(id?.toString() ?? "null")}`;
}
