/**
 * 정부 직책 목업 데이터
 */

/**
 * 직업 타입 목록 (목업)
 */
export const MOCK_POSITION_TYPES = [
  { value: 'HEAD_OF_STATE', label: '국가원수' },
  { value: 'HEAD_OF_GOVERNMENT', label: '정부수반' },
  { value: 'CABINET_MINISTER', label: '각료/장관' },
  { value: 'VICE_MINISTER', label: '차관' },
  { value: 'LEGISLATOR', label: '의회의원' },
  { value: 'JUDICIARY', label: '사법부' },
  { value: 'LOCAL_GOVERNMENT', label: '지방정부' },
  { value: 'SPECIAL_POSITION', label: '특별직' },
  { value: 'MILITARY_COMMANDER', label: '군 지휘관' },
  { value: 'OTHER', label: '기타' },
]

export const MOCK_PERSONS_WITH_GOVERNMENT_POSITIONS = [
  {
    id: 'person-1',
    name: '루스벨트',
    surname: '프랭클린 D.',
    profileImageUrl: null,
    governmentPositions: [
      {
        id: 'tenure-1',
        termNumber: 32,
        startDate: '1933-03-04T00:00:00.000Z',
        endDate: '1945-04-12T00:00:00.000Z',
        appointmentMethod: 'DIRECT_ELECTION',
        endReason: '사망',
        notes: '뉴딜 정책, 제2차 세계대전 지도',
        priority: 0,
        position: {
          id: 'pos-1',
          title: '대통령',
          titleEn: 'President',
          positionType: 'HEAD_OF_STATE',
          rank: 1,
          description: '미합중국 대통령',
          departmentName: null,
          country: {
            id: 'country-usa',
            name: '미국',
            isoCode: 'US',
          },
          historicalCountry: null,
        },
      },
    ],
  },
  {
    id: 'person-2',
    name: '처칠',
    surname: '윈스턴',
    profileImageUrl: null,
    governmentPositions: [
      {
        id: 'tenure-2',
        termNumber: null,
        startDate: '1940-05-10T00:00:00.000Z',
        endDate: '1945-07-26T00:00:00.000Z',
        appointmentMethod: 'PARLIAMENTARY_ELECTION',
        endReason: '선거 패배',
        notes: '제2차 세계대전 승리',
        priority: 0,
        position: {
          id: 'pos-2',
          title: '총리',
          titleEn: 'Prime Minister',
          positionType: 'HEAD_OF_GOVERNMENT',
          rank: 1,
          description: '영국 총리',
          departmentName: null,
          country: {
            id: 'country-uk',
            name: '영국',
            isoCode: 'GB',
          },
          historicalCountry: null,
        },
      },
    ],
  },
  {
    id: 'person-3',
    name: '스탈린',
    surname: '이오시프',
    profileImageUrl: null,
    governmentPositions: [
      {
        id: 'tenure-3',
        termNumber: null,
        startDate: '1922-04-03T00:00:00.000Z',
        endDate: '1953-03-05T00:00:00.000Z',
        appointmentMethod: 'OTHER',
        endReason: '사망',
        notes: '소련 공산당 서기장',
        priority: 0,
        position: {
          id: 'pos-3',
          title: '최고 지도자',
          titleEn: 'General Secretary',
          positionType: 'HEAD_OF_STATE',
          rank: 1,
          description: '소련 공산당 서기장',
          departmentName: null,
          country: null,
          historicalCountry: {
            id: 'country-ussr',
            name: '소련',
          },
        },
      },
    ],
  },
  {
    id: 'person-4',
    name: '히틀러',
    surname: '아돌프',
    profileImageUrl: null,
    governmentPositions: [
      {
        id: 'tenure-4',
        termNumber: null,
        startDate: '1934-08-02T00:00:00.000Z',
        endDate: '1945-04-30T00:00:00.000Z',
        appointmentMethod: 'OTHER',
        endReason: '자살',
        notes: '나치 독일 총통',
        priority: 0,
        position: {
          id: 'pos-4',
          title: '총통',
          titleEn: 'Führer',
          positionType: 'HEAD_OF_STATE',
          rank: 1,
          description: '나치 독일 총통',
          departmentName: null,
          country: null,
          historicalCountry: {
            id: 'country-nazi',
            name: '나치 독일',
          },
        },
      },
    ],
  },
  {
    id: 'person-5',
    name: '도조 히데키',
    surname: null,
    profileImageUrl: null,
    governmentPositions: [
      {
        id: 'tenure-5',
        termNumber: 40,
        startDate: '1941-10-18T00:00:00.000Z',
        endDate: '1944-07-22T00:00:00.000Z',
        appointmentMethod: 'APPOINTMENT',
        endReason: '사임',
        notes: '태평양 전쟁 개시',
        priority: 0,
        position: {
          id: 'pos-5',
          title: '내각총리대신',
          titleEn: 'Prime Minister',
          positionType: 'HEAD_OF_GOVERNMENT',
          rank: 1,
          description: '일본 내각총리대신',
          departmentName: null,
          country: {
            id: 'country-japan',
            name: '일본',
            isoCode: 'JP',
          },
          historicalCountry: null,
        },
      },
    ],
  },
  {
    id: 'person-6',
    name: '무솔리니',
    surname: '베니토',
    profileImageUrl: null,
    governmentPositions: [
      {
        id: 'tenure-6',
        termNumber: null,
        startDate: '1922-10-31T00:00:00.000Z',
        endDate: '1943-07-25T00:00:00.000Z',
        appointmentMethod: 'OTHER',
        endReason: '해임',
        notes: '이탈리아 파시스트 정권',
        priority: 0,
        position: {
          id: 'pos-6',
          title: '총리',
          titleEn: 'Prime Minister',
          positionType: 'HEAD_OF_GOVERNMENT',
          rank: 1,
          description: '이탈리아 총리',
          departmentName: null,
          country: {
            id: 'country-italy',
            name: '이탈리아',
            isoCode: 'IT',
          },
          historicalCountry: null,
        },
      },
    ],
  },
  {
    id: 'person-7',
    name: '드골',
    surname: '샤를',
    profileImageUrl: null,
    governmentPositions: [
      {
        id: 'tenure-7',
        termNumber: null,
        startDate: '1944-06-03T00:00:00.000Z',
        endDate: '1946-01-20T00:00:00.000Z',
        appointmentMethod: 'OTHER',
        endReason: '사임',
        notes: '자유 프랑스 지도자',
        priority: 0,
        position: {
          id: 'pos-7',
          title: '임시정부 수반',
          titleEn: 'Head of Provisional Government',
          positionType: 'HEAD_OF_GOVERNMENT',
          rank: 1,
          description: '프랑스 임시정부 수반',
          departmentName: null,
          country: {
            id: 'country-france',
            name: '프랑스',
            isoCode: 'FR',
          },
          historicalCountry: null,
        },
      },
    ],
  },
  {
    id: 'person-8',
    name: '트루먼',
    surname: '해리',
    profileImageUrl: null,
    governmentPositions: [
      {
        id: 'tenure-8',
        termNumber: 33,
        startDate: '1945-04-12T00:00:00.000Z',
        endDate: '1953-01-20T00:00:00.000Z',
        appointmentMethod: 'DIRECT_ELECTION',
        endReason: '임기 만료',
        notes: '원폭 투하 결정, 냉전 시작',
        priority: 0,
        position: {
          id: 'pos-1',
          title: '대통령',
          titleEn: 'President',
          positionType: 'HEAD_OF_STATE',
          rank: 1,
          description: '미합중국 대통령',
          departmentName: null,
          country: {
            id: 'country-usa',
            name: '미국',
            isoCode: 'US',
          },
          historicalCountry: null,
        },
      },
    ],
  },
]
