/**
 * @packageDocumentation
 * @module api.functional.social.comments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * @controller SocialController.getComments
 * @path GET /social/comments/:curationId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getComments(
  connection: IConnection,
  curationId: string,
  page: string,
  pageSize: string,
): Promise<getComments.Output> {
  return PlainFetcher.fetch(connection, {
    ...getComments.METADATA,
    template: getComments.METADATA.path,
    path: getComments.path(curationId, page, pageSize),
  });
}
export namespace getComments {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "GET",
    path: "/social/comments/:curationId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (curationId: string, page: string, pageSize: string) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      page: page,
      pageSize: pageSize,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/social/comments/${encodeURIComponent(curationId?.toString() ?? "null")}`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
