/**
 * @packageDocumentation
 * @module api.functional.curations.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { PaginatedCurationResponse } from "../../../../libs/curation/presentation/curation.controller";

/**
 * @controller CurationController.getUserCurations
 * @path GET /curations/user/:userId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUserCurations(
  connection: IConnection,
  userId: string,
  page: string,
  pageSize: string,
): Promise<getUserCurations.Output> {
  return PlainFetcher.fetch(connection, {
    ...getUserCurations.METADATA,
    template: getUserCurations.METADATA.path,
    path: getUserCurations.path(userId, page, pageSize),
  });
}
export namespace getUserCurations {
  export type Output = Primitive<PaginatedCurationResponse>;

  export const METADATA = {
    method: "GET",
    path: "/curations/user/:userId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (userId: string, page: string, pageSize: string) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      page: page,
      pageSize: pageSize,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/curations/user/${encodeURIComponent(userId?.toString() ?? "null")}`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
