/**
 * @packageDocumentation
 * @module api.functional.jobs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreateJobDto,
  JobResponseDto,
  UpdateJobDto,
} from "../../../libs/job/presentation/dto";

/**
 * @controller JobController.getAll
 * @path GET /jobs
 * @accessor api.functional.jobs.getAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAll(connection: IConnection): Promise<getAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAll.METADATA,
    template: getAll.METADATA.path,
    path: getAll.path(),
  });
}
export namespace getAll {
  export type Output = Primitive<Array<JobResponseDto>>;

  export const METADATA = {
    method: "GET",
    path: "/jobs",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/jobs";
}

/**
 * @controller JobController.getById
 * @path GET /jobs/:id
 * @accessor api.functional.jobs.getById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getById(
  connection: IConnection,
  id: string,
): Promise<getById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getById.METADATA,
    template: getById.METADATA.path,
    path: getById.path(id),
  });
}
export namespace getById {
  export type Output = Primitive<JobResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/jobs/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/jobs/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller JobController.create
 * @path POST /jobs
 * @accessor api.functional.jobs.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  dto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    dto,
  );
}
export namespace create {
  export type Body = Primitive<CreateJobDto>;
  export type Output = Primitive<JobResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/jobs",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/jobs";
}

/**
 * @controller JobController.update
 * @path PUT /jobs/:id
 * @accessor api.functional.jobs.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  dto: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    dto,
  );
}
export namespace update {
  export type Body = Primitive<UpdateJobDto>;
  export type Output = Primitive<JobResponseDto>;

  export const METADATA = {
    method: "PUT",
    path: "/jobs/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/jobs/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller JobController._delete
 * @path DELETE /jobs/:id
 * @accessor api.functional.jobs._delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function _delete(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ..._delete.METADATA,
    template: _delete.METADATA.path,
    path: _delete.path(id),
  });
}
export namespace _delete {
  export const METADATA = {
    method: "DELETE",
    path: "/jobs/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string) =>
    `/jobs/${encodeURIComponent(id?.toString() ?? "null")}`;
}
