/**
 * @packageDocumentation
 * @module api.functional.dynasties
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreateDynastyDto,
  DynastyResponseDto,
  UpdateDynastyDto,
} from "../../../libs/dynasty/presentation/dto";

export * as detail from "./detail/index";

/**
 * @controller DynastyController.getAll
 * @path GET /dynasties
 * @accessor api.functional.dynasties.getAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAll(connection: IConnection): Promise<getAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAll.METADATA,
    template: getAll.METADATA.path,
    path: getAll.path(),
  });
}
export namespace getAll {
  export type Output = Primitive<Array<DynastyResponseDto>>;

  export const METADATA = {
    method: "GET",
    path: "/dynasties",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/dynasties";
}

/**
 * @controller DynastyController.getById
 * @path GET /dynasties/:id
 * @accessor api.functional.dynasties.getById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getById(
  connection: IConnection,
  id: string,
): Promise<getById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getById.METADATA,
    template: getById.METADATA.path,
    path: getById.path(id),
  });
}
export namespace getById {
  export type Output = Primitive<DynastyResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/dynasties/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/dynasties/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller DynastyController.create
 * @path POST /dynasties
 * @accessor api.functional.dynasties.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  dto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    dto,
  );
}
export namespace create {
  export type Body = Primitive<CreateDynastyDto>;
  export type Output = Primitive<DynastyResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/dynasties",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/dynasties";
}

/**
 * @controller DynastyController.update
 * @path PUT /dynasties/:id
 * @accessor api.functional.dynasties.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  dto: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    dto,
  );
}
export namespace update {
  export type Body = Primitive<UpdateDynastyDto>;
  export type Output = Primitive<DynastyResponseDto>;

  export const METADATA = {
    method: "PUT",
    path: "/dynasties/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/dynasties/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller DynastyController._delete
 * @path DELETE /dynasties/:id
 * @accessor api.functional.dynasties._delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function _delete(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ..._delete.METADATA,
    template: _delete.METADATA.path,
    path: _delete.path(id),
  });
}
export namespace _delete {
  export const METADATA = {
    method: "DELETE",
    path: "/dynasties/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string) =>
    `/dynasties/${encodeURIComponent(id?.toString() ?? "null")}`;
}
