/**
 * @packageDocumentation
 * @module api.functional.social.like
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * @controller SocialController.like
 * @path POST /social/like/:curationId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function like(
  connection: IConnection,
  curationId: string,
): Promise<like.Output> {
  return PlainFetcher.fetch(connection, {
    ...like.METADATA,
    template: like.METADATA.path,
    path: like.path(curationId),
  });
}
export namespace like {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "POST",
    path: "/social/like/:curationId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (curationId: string) =>
    `/social/like/${encodeURIComponent(curationId?.toString() ?? "null")}`;
}

/**
 * @controller SocialController.unlike
 * @path DELETE /social/like/:curationId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function unlike(
  connection: IConnection,
  curationId: string,
): Promise<unlike.Output> {
  return PlainFetcher.fetch(connection, {
    ...unlike.METADATA,
    template: unlike.METADATA.path,
    path: unlike.path(curationId),
  });
}
export namespace unlike {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "DELETE",
    path: "/social/like/:curationId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (curationId: string) =>
    `/social/like/${encodeURIComponent(curationId?.toString() ?? "null")}`;
}
