/**
 * @packageDocumentation
 * @module api.functional.persons
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreatePersonDto,
  PersonResponseDto,
  UpdatePersonDto,
} from "../../../libs/person/presentation/dto";

export * as with_government_positions from "./with_government_positions/index";
export * as dashboard from "./dashboard/index";
export * as tenures from "./tenures/index";
export * as human_relationships from "./human_relationships/index";
export * as family_tree from "./family_tree/index";
export * as detail from "./detail/index";
export * as careers from "./careers/index";
export * as educations from "./educations/index";
export * as awards from "./awards/index";
export * as by_dynasty from "./by_dynasty/index";
export * as by_country from "./by_country/index";
export * as political_party_memberships from "./political_party_memberships/index";
export * as election_candidacies from "./election_candidacies/index";

/**
 * 인물 목록 조회 (본인 등록분만)
 * @controller PersonController.getAll
 * @path GET /persons
 * @accessor api.functional.persons.getAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAll(connection: IConnection): Promise<getAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAll.METADATA,
    template: getAll.METADATA.path,
    path: getAll.path(),
  });
}
export namespace getAll {
  export type Output = Primitive<Array<PersonResponseDto>>;

  export const METADATA = {
    method: "GET",
    path: "/persons",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/persons";
}

/**
 * ID로 인물 조회 (본인 등록분만)
 * @controller PersonController.getById
 * @path GET /persons/:id
 * @accessor api.functional.persons.getById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getById(
  connection: IConnection,
  id: string,
): Promise<getById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getById.METADATA,
    template: getById.METADATA.path,
    path: getById.path(id),
  });
}
export namespace getById {
  export type Output = Primitive<PersonResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/persons/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/persons/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 인물 생성 (현재 계정 소유로 등록)
 * @controller PersonController.create
 * @path POST /persons
 * @accessor api.functional.persons.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  dto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    dto,
  );
}
export namespace create {
  export type Body = Primitive<CreatePersonDto>;
  export type Output = Primitive<PersonResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/persons",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/persons";
}

/**
 * 인물 수정 (본인 등록분만)
 * @controller PersonController.update
 * @path PUT /persons/:id
 * @accessor api.functional.persons.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  dto: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    dto,
  );
}
export namespace update {
  export type Body = Primitive<UpdatePersonDto>;
  export type Output = Primitive<PersonResponseDto>;

  export const METADATA = {
    method: "PUT",
    path: "/persons/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/persons/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 인물 삭제 (본인 등록분만)
 * @controller PersonController._delete
 * @path DELETE /persons/:id
 * @accessor api.functional.persons._delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function _delete(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ..._delete.METADATA,
    template: _delete.METADATA.path,
    path: _delete.path(id),
  });
}
export namespace _delete {
  export const METADATA = {
    method: "DELETE",
    path: "/persons/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string) =>
    `/persons/${encodeURIComponent(id?.toString() ?? "null")}`;
}
