/**
 * @packageDocumentation
 * @module api.functional.users.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { UserResponseDto } from "../../../../libs/user/presentation/dto/user-response.dto";
import type { UpdateProfileDto } from "../../../../libs/user/presentation/dto/user.dto";

export * as password from "./password/index";

/**
 * 현재 사용자 정보 조회
 * @controller UserController.getMe
 * @path GET /users/me
 * @accessor api.functional.users.me.getMe
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMe(connection: IConnection): Promise<getMe.Output> {
  return PlainFetcher.fetch(connection, {
    ...getMe.METADATA,
    template: getMe.METADATA.path,
    path: getMe.path(),
  });
}
export namespace getMe {
  export type Output = Primitive<UserResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/users/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/users/me";
}

/**
 * 프로필 업데이트
 * @controller UserController.updateProfile
 * @path PUT /users/me
 * @accessor api.functional.users.me.updateProfile
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateProfile(
  connection: IConnection,
  dto: updateProfile.Body,
): Promise<updateProfile.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateProfile.METADATA,
      template: updateProfile.METADATA.path,
      path: updateProfile.path(),
    },
    dto,
  );
}
export namespace updateProfile {
  export type Body = Primitive<UpdateProfileDto>;
  export type Output = Primitive<UserResponseDto>;

  export const METADATA = {
    method: "PUT",
    path: "/users/me",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/users/me";
}

/**
 * 계정 비활성화 (탈퇴)
 * @controller UserController.deactivate
 * @path DELETE /users/me
 * @accessor api.functional.users.me.deactivate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deactivate(
  connection: IConnection,
): Promise<deactivate.Output> {
  return PlainFetcher.fetch(connection, {
    ...deactivate.METADATA,
    template: deactivate.METADATA.path,
    path: deactivate.path(),
  });
}
export namespace deactivate {
  export type Output = Primitive<{ message: string }>;

  export const METADATA = {
    method: "DELETE",
    path: "/users/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/users/me";
}
