/**
 * @packageDocumentation
 * @module api.functional.events
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreateEventDto,
  EventResponseDto,
  UpdateEventDto,
} from "../../../libs/event/presentation/dto";

export * as parent from "./parent/index";
export * as deleted from "./deleted/index";
export * as restore from "./restore/index";
export * as permanent from "./permanent/index";

/**
 * 모든 사건 조회 (페이징 지원)
 *
 * @param offset 시작 위치 (기본값: 0)
 * @param limit 가져올 개수 (기본값: 20, 최대: 100)
 * @returns 사건 목록
 * @tag events
 *
 * @controller EventController.getAllEvents
 * @path GET /events
 * @accessor api.functional.events.getAllEvents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllEvents(
  connection: IConnection,
  offset?: string,
  limit?: string,
  createdSinceDays?: string,
): Promise<getAllEvents.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAllEvents.METADATA,
    template: getAllEvents.METADATA.path,
    path: getAllEvents.path(offset, limit, createdSinceDays),
  });
}
export namespace getAllEvents {
  export type Output = Primitive<Array<EventResponseDto>>;

  export const METADATA = {
    method: "GET",
    path: "/events",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    offset?: string,
    limit?: string,
    createdSinceDays?: string,
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      offset: offset,
      limit: limit,
      createdSinceDays: createdSinceDays,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/events";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * 사건 상세 조회
 *
 * @param id 사건 ID
 * @returns 사건 정보
 * @tag events
 *
 * @controller EventController.getEventById
 * @path GET /events/:id
 * @accessor api.functional.events.getEventById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getEventById(
  connection: IConnection,
  id: string,
): Promise<getEventById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getEventById.METADATA,
    template: getEventById.METADATA.path,
    path: getEventById.path(id),
  });
}
export namespace getEventById {
  export type Output = Primitive<EventResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/events/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/events/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 사건 생성
 *
 * @param dto 사건 생성 정보
 * @returns 생성된 사건
 * @tag events
 *
 * @controller EventController.createEvent
 * @path POST /events
 * @accessor api.functional.events.createEvent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createEvent(
  connection: IConnection,
  dto: createEvent.Body,
): Promise<createEvent.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createEvent.METADATA,
      template: createEvent.METADATA.path,
      path: createEvent.path(),
    },
    dto,
  );
}
export namespace createEvent {
  export type Body = Primitive<CreateEventDto>;
  export type Output = Primitive<EventResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/events",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/events";
}

/**
 * 사건 수정
 *
 * @param id 사건 ID
 * @param dto 사건 수정 정보
 * @returns 수정된 사건
 * @tag events
 *
 * @controller EventController.updateEvent
 * @path PUT /events/:id
 * @accessor api.functional.events.updateEvent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateEvent(
  connection: IConnection,
  id: string,
  dto: updateEvent.Body,
): Promise<updateEvent.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateEvent.METADATA,
      template: updateEvent.METADATA.path,
      path: updateEvent.path(id),
    },
    dto,
  );
}
export namespace updateEvent {
  export type Body = Primitive<UpdateEventDto>;
  export type Output = Primitive<EventResponseDto>;

  export const METADATA = {
    method: "PUT",
    path: "/events/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/events/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 사건 삭제
 *
 * @param id 사건 ID
 * @tag events
 *
 * @controller EventController.deleteEvent
 * @path DELETE /events/:id
 * @accessor api.functional.events.deleteEvent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteEvent(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteEvent.METADATA,
    template: deleteEvent.METADATA.path,
    path: deleteEvent.path(id),
  });
}
export namespace deleteEvent {
  export const METADATA = {
    method: "DELETE",
    path: "/events/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string) =>
    `/events/${encodeURIComponent(id?.toString() ?? "null")}`;
}
