/**
 * @packageDocumentation
 * @module api.functional.job_categories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreateJobCategoryDto,
  JobCategoryResponseDto,
  UpdateJobCategoryDto,
} from "../../../libs/job-category/presentation/dto";

/**
 * @controller JobCategoryController.getAll
 * @path GET /job-categories
 * @accessor api.functional.job_categories.getAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAll(connection: IConnection): Promise<getAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAll.METADATA,
    template: getAll.METADATA.path,
    path: getAll.path(),
  });
}
export namespace getAll {
  export type Output = Primitive<Array<JobCategoryResponseDto>>;

  export const METADATA = {
    method: "GET",
    path: "/job-categories",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/job-categories";
}

/**
 * @controller JobCategoryController.getById
 * @path GET /job-categories/:id
 * @accessor api.functional.job_categories.getById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getById(
  connection: IConnection,
  id: string,
): Promise<getById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getById.METADATA,
    template: getById.METADATA.path,
    path: getById.path(id),
  });
}
export namespace getById {
  export type Output = Primitive<JobCategoryResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/job-categories/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/job-categories/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller JobCategoryController.create
 * @path POST /job-categories
 * @accessor api.functional.job_categories.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  dto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    dto,
  );
}
export namespace create {
  export type Body = Primitive<CreateJobCategoryDto>;
  export type Output = Primitive<JobCategoryResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/job-categories",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/job-categories";
}

/**
 * @controller JobCategoryController.update
 * @path PUT /job-categories/:id
 * @accessor api.functional.job_categories.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  dto: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    dto,
  );
}
export namespace update {
  export type Body = Primitive<UpdateJobCategoryDto>;
  export type Output = Primitive<JobCategoryResponseDto>;

  export const METADATA = {
    method: "PUT",
    path: "/job-categories/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/job-categories/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller JobCategoryController._delete
 * @path DELETE /job-categories/:id
 * @accessor api.functional.job_categories._delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function _delete(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ..._delete.METADATA,
    template: _delete.METADATA.path,
    path: _delete.path(id),
  });
}
export namespace _delete {
  export const METADATA = {
    method: "DELETE",
    path: "/job-categories/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string) =>
    `/job-categories/${encodeURIComponent(id?.toString() ?? "null")}`;
}
