/**
 * @packageDocumentation
 * @module api.functional.event_categories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { EventCategoryResponse } from '../../../libs/event-category/presentation/event-category.controller'

/**
 * @controller EventCategoryController.getAllCategories
 * @path GET /event-categories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllCategories(
  connection: IConnection,
): Promise<getAllCategories.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAllCategories.METADATA,
    template: getAllCategories.METADATA.path,
    path: getAllCategories.path(),
  });
}
export namespace getAllCategories {
  export type Output = Primitive<EventCategoryResponse[]>;

  export const METADATA = {
    method: "GET",
    path: "/event-categories",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/event-categories";
}
