/**
 * @packageDocumentation
 * @module api.functional.continents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { ContinentResponseDto } from "../../../libs/continent/presentation/dto/continent.response";
import type { CreateContinentDto } from "../../../libs/continent/presentation/dto/create-continent.dto";
import type { UpdateContinentDto } from "../../../libs/continent/presentation/dto/update-continent.dto";

/**
 * 모든 대륙 조회
 *
 * @returns 대륙 목록
 * @tag continents
 *
 * @controller ContinentController.getAllContinents
 * @path GET /continents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllContinents(
  connection: IConnection,
): Promise<getAllContinents.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAllContinents.METADATA,
    template: getAllContinents.METADATA.path,
    path: getAllContinents.path(),
  });
}
export namespace getAllContinents {
  export type Output = Primitive<ContinentResponseDto[]>;

  export const METADATA = {
    method: "GET",
    path: "/continents",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/continents";
}

/**
 * 대륙 상세 조회
 *
 * @param id 대륙 ID
 * @returns 대륙 정보
 * @tag continents
 *
 * @controller ContinentController.getContinentById
 * @path GET /continents/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getContinentById(
  connection: IConnection,
  id: string,
): Promise<getContinentById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getContinentById.METADATA,
    template: getContinentById.METADATA.path,
    path: getContinentById.path(id),
  });
}
export namespace getContinentById {
  export type Output = Primitive<ContinentResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/continents/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/continents/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 대륙 생성
 *
 * @param dto 대륙 생성 정보
 * @returns 생성된 대륙
 * @tag continents
 *
 * @controller ContinentController.createContinent
 * @path POST /continents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createContinent(
  connection: IConnection,
  dto: createContinent.Body,
): Promise<createContinent.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createContinent.METADATA,
      template: createContinent.METADATA.path,
      path: createContinent.path(),
    },
    dto,
  );
}
export namespace createContinent {
  export type Body = Primitive<CreateContinentDto>;
  export type Output = Primitive<ContinentResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/continents",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/continents";
}

/**
 * 대륙 수정
 *
 * @param id 대륙 ID
 * @param dto 대륙 수정 정보
 * @returns 수정된 대륙
 * @tag continents
 *
 * @controller ContinentController.updateContinent
 * @path PUT /continents/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateContinent(
  connection: IConnection,
  id: string,
  dto: updateContinent.Body,
): Promise<updateContinent.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateContinent.METADATA,
      template: updateContinent.METADATA.path,
      path: updateContinent.path(id),
    },
    dto,
  );
}
export namespace updateContinent {
  export type Body = Primitive<UpdateContinentDto>;
  export type Output = Primitive<ContinentResponseDto>;

  export const METADATA = {
    method: "PUT",
    path: "/continents/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/continents/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 대륙 삭제
 *
 * @param id 대륙 ID
 * @tag continents
 *
 * @controller ContinentController.deleteContinent
 * @path DELETE /continents/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteContinent(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteContinent.METADATA,
    template: deleteContinent.METADATA.path,
    path: deleteContinent.path(id),
  });
}
export namespace deleteContinent {
  export const METADATA = {
    method: "DELETE",
    path: "/continents/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string) =>
    `/continents/${encodeURIComponent(id?.toString() ?? "null")}`;
}
