/**
 * @packageDocumentation
 * @module api.functional.social.comment.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { UpdateCommentDto } from "../../../../../libs/social/presentation/social.controller";

/**
 * @controller SocialController.updateComment
 * @path POST /social/comment/:commentId/update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateComment(
  connection: IConnection,
  commentId: string,
  dto: updateComment.Body,
): Promise<updateComment.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateComment.METADATA,
      template: updateComment.METADATA.path,
      path: updateComment.path(commentId),
    },
    dto,
  );
}
export namespace updateComment {
  export type Body = Primitive<UpdateCommentDto>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "POST",
    path: "/social/comment/:commentId/update",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (commentId: string) =>
    `/social/comment/${encodeURIComponent(commentId?.toString() ?? "null")}/update`;
}
