/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

export * as users from "./users/index";
export * as social from "./social/index";
export * as treaties from "./treaties/index";
export * as upload from "./upload/index";
export * as health from "./health/index";
export * as religions from "./religions/index";
export * as persons from "./persons/index";
export * as government_positions from "./government_positions/index";
export * as organizations from "./organizations/index";
export * as notifications from "./notifications/index";
export * as job_categories from "./job_categories/index";
export * as jobs from "./jobs/index";
export * as historical_countries from "./historical_countries/index";
export * as event_categories from "./event_categories/index";
export * as glossary from "./glossary/index";
export * as ethnicities from "./ethnicities/index";
export * as political_parties from "./political_parties/index";
export * as political_party_transitions from "./political_party_transitions/index";
export * as laws from "./laws/index";
export * as law_types from "./law_types/index";
export * as electoral_districts from "./electoral_districts/index";
export * as elections from "./elections/index";
export * as entity_link_search from "./entity_link_search/index";
export * as events from "./events/index";
export * as dynasties from "./dynasties/index";
export * as posts from "./posts/index";
export * as countries from "./countries/index";
export * as continents from "./continents/index";
export * as cities from "./cities/index";
export * as auth from "./auth/index";
export * as account from "./account/index";
export * as administration_departments from "./administration_departments/index";
export * as uploads from "./uploads/index";
export * as military_units from "./military_units/index";

/**
 * @controller AppController.getRoot
 * @path GET /
 * @accessor api.functional.getRoot
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getRoot(
  connection: IConnection,
): Promise<getRoot.Output> {
  return PlainFetcher.fetch(connection, {
    ...getRoot.METADATA,
    template: getRoot.METADATA.path,
    path: getRoot.path(),
  });
}
export namespace getRoot {
  export type Output = Primitive<{
    name: string;
    version: string;
    description: string;
    endpoints: {
      health: string;
      docs: string;
    };
  }>;

  export const METADATA = {
    method: "GET",
    path: "/",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/";
}
