import { PrismaService } from '../prisma.service'

const ACCOUNT_ID = '6af53fe7-d02b-4c42-b86c-f32800897b32'

export interface CountryData {
  name: string
  localName: string
  flagEmoji: string
  isoCode: string
  population: number
  areaSqKm: number
  continentName: string
}

/**
 * 성(姓)을 먼저 쓰는 문화권 ISO 코드.
 * 여기 속하면 korean(성+이름), 나머지는 모두 western(이름+성)으로 표시.
 * 개별 인물 예외는 Person.nameDisplayOrder로 오버라이드한다.
 */
const FAMILY_NAME_FIRST_ISO = new Set(['KR', 'JP', 'CN', 'VN'])

function nameOrderFor(isoCode: string): 'korean' | 'western' {
  return FAMILY_NAME_FIRST_ISO.has(isoCode) ? 'korean' : 'western'
}

const COUNTRIES: CountryData[] = [
  {
    name: '대한민국',
    localName: '대한민국',
    flagEmoji: '🇰🇷',
    isoCode: 'KR',
    population: 51780579,
    areaSqKm: 100210.0,
    continentName: '아시아',
  },
  {
    name: '일본',
    localName: '日本',
    flagEmoji: '🇯🇵',
    isoCode: 'JP',
    population: 125584838,
    areaSqKm: 377975.0,
    continentName: '아시아',
  },
  {
    name: '중국',
    localName: '中国',
    flagEmoji: '🇨🇳',
    isoCode: 'CN',
    population: 1412175000,
    areaSqKm: 9596961.0,
    continentName: '아시아',
  },
  {
    name: '이란',
    localName: 'ایران',
    flagEmoji: '🇮🇷',
    isoCode: 'IR',
    population: 89172767,
    areaSqKm: 1648195.0,
    continentName: '아시아',
  },
  {
    name: '이스라엘',
    localName: 'יִשְׂרָאֵל',
    flagEmoji: '🇮🇱',
    isoCode: 'IL',
    population: 9842000,
    areaSqKm: 22072.0,
    continentName: '아시아',
  },
  {
    name: '카타르',
    localName: 'قطر',
    flagEmoji: '🇶🇦',
    isoCode: 'QA',
    population: 2716391,
    areaSqKm: 11586.0,
    continentName: '아시아',
  },
  {
    name: '사우디아라비아',
    localName: 'المملكة العربية السعودية',
    flagEmoji: '🇸🇦',
    isoCode: 'SA',
    population: 36947025,
    areaSqKm: 2149690.0,
    continentName: '아시아',
  },
  {
    name: '시리아',
    localName: 'سُورِيَا',
    flagEmoji: '🇸🇾',
    isoCode: 'SY',
    population: 23227014,
    areaSqKm: 185180.0,
    continentName: '아시아',
  },
  {
    name: '레바논',
    localName: 'لبنان',
    flagEmoji: '🇱🇧',
    isoCode: 'LB',
    population: 5489739,
    areaSqKm: 10452.0,
    continentName: '아시아',
  },
  {
    name: '팔레스타인',
    localName: 'فلسطين',
    flagEmoji: '🇵🇸',
    isoCode: 'PS',
    population: 5483450,
    areaSqKm: 6020.0,
    continentName: '아시아',
  },
  {
    name: '예멘',
    localName: 'اليمن',
    flagEmoji: '🇾🇪',
    isoCode: 'YE',
    population: 33696614,
    areaSqKm: 527968.0,
    continentName: '아시아',
  },
  {
    name: '이라크',
    localName: 'العراق',
    flagEmoji: '🇮🇶',
    isoCode: 'IQ',
    population: 43533592,
    areaSqKm: 438317.0,
    continentName: '아시아',
  },
  {
    name: '미국',
    localName: 'United States',
    flagEmoji: '🇺🇸',
    isoCode: 'US',
    population: 334914895,
    areaSqKm: 9833520.0,
    continentName: '북아메리카',
  },
  {
    name: '영국',
    localName: 'United Kingdom',
    flagEmoji: '🇬🇧',
    isoCode: 'GB',
    population: 68497907,
    areaSqKm: 242495.0,
    continentName: '유럽',
  },
  {
    name: '프랑스',
    localName: 'France',
    flagEmoji: '🇫🇷',
    isoCode: 'FR',
    population: 67935660,
    areaSqKm: 643801.0,
    continentName: '유럽',
  },
  {
    name: '독일',
    localName: 'Deutschland',
    flagEmoji: '🇩🇪',
    isoCode: 'DE',
    population: 84482267,
    areaSqKm: 357592.0,
    continentName: '유럽',
  },
  {
    name: '러시아',
    localName: 'Россия',
    flagEmoji: '🇷🇺',
    isoCode: 'RU',
    population: 144444359,
    areaSqKm: 17098242.0,
    continentName: '유럽',
  },
  {
    name: '튀르키예',
    localName: 'Türkiye',
    flagEmoji: '🇹🇷',
    isoCode: 'TR',
    population: 85816199,
    areaSqKm: 783562.0,
    continentName: '유럽',
  },
  {
    name: '헝가리',
    localName: 'Magyarország',
    flagEmoji: '🇭🇺',
    isoCode: 'HU',
    population: 9597085,
    areaSqKm: 93030.0,
    continentName: '유럽',
  },
  {
    name: '오스트리아',
    localName: 'Österreich',
    flagEmoji: '🇦🇹',
    isoCode: 'AT',
    population: 9120813,
    areaSqKm: 83879.0,
    continentName: '유럽',
  },
  {
    name: '루마니아',
    localName: 'România',
    flagEmoji: '🇷🇴',
    isoCode: 'RO',
    population: 19056116,
    areaSqKm: 238397.0,
    continentName: '유럽',
  },
  {
    name: '불가리아',
    localName: 'България',
    flagEmoji: '🇧🇬',
    isoCode: 'BG',
    population: 6838937,
    areaSqKm: 110879.0,
    continentName: '유럽',
  },
  {
    name: '세르비아',
    localName: 'Србија',
    flagEmoji: '🇷🇸',
    isoCode: 'RS',
    population: 6641197,
    areaSqKm: 88361.0,
    continentName: '유럽',
  },
  {
    name: '폴란드',
    localName: 'Polska',
    flagEmoji: '🇵🇱',
    isoCode: 'PL',
    population: 38036118,
    areaSqKm: 312696.0,
    continentName: '유럽',
  },
  {
    name: '체코',
    localName: 'Česko',
    flagEmoji: '🇨🇿',
    isoCode: 'CZ',
    population: 10873689,
    areaSqKm: 78871.0,
    continentName: '유럽',
  },
  {
    name: '슬로바키아',
    localName: 'Slovensko',
    flagEmoji: '🇸🇰',
    isoCode: 'SK',
    population: 5460185,
    areaSqKm: 49037.0,
    continentName: '유럽',
  },
  {
    name: '네덜란드',
    localName: 'Nederland',
    flagEmoji: '🇳🇱',
    isoCode: 'NL',
    population: 17811291,
    areaSqKm: 41850.0,
    continentName: '유럽',
  },
  {
    name: '벨기에',
    localName: 'België / Belgique',
    flagEmoji: '🇧🇪',
    isoCode: 'BE',
    population: 11697557,
    areaSqKm: 30528.0,
    continentName: '유럽',
  },
  {
    name: '핀란드',
    localName: 'Suomi',
    flagEmoji: '🇫🇮',
    isoCode: 'FI',
    population: 5563970,
    areaSqKm: 338455.0,
    continentName: '유럽',
  },
  // === Top 30 by population (추가분) ===
  {
    name: '인도',
    localName: 'भारत',
    flagEmoji: '🇮🇳',
    isoCode: 'IN',
    population: 1428627663,
    areaSqKm: 3287263.0,
    continentName: '아시아',
  },
  {
    name: '인도네시아',
    localName: 'Indonesia',
    flagEmoji: '🇮🇩',
    isoCode: 'ID',
    population: 277534122,
    areaSqKm: 1904569.0,
    continentName: '아시아',
  },
  {
    name: '파키스탄',
    localName: 'پاکستان',
    flagEmoji: '🇵🇰',
    isoCode: 'PK',
    population: 240485658,
    areaSqKm: 881913.0,
    continentName: '아시아',
  },
  {
    name: '나이지리아',
    localName: 'Nigeria',
    flagEmoji: '🇳🇬',
    isoCode: 'NG',
    population: 223804632,
    areaSqKm: 923768.0,
    continentName: '아프리카',
  },
  {
    name: '브라질',
    localName: 'Brasil',
    flagEmoji: '🇧🇷',
    isoCode: 'BR',
    population: 216422446,
    areaSqKm: 8515767.0,
    continentName: '남아메리카',
  },
  {
    name: '방글라데시',
    localName: 'বাংলাদেশ',
    flagEmoji: '🇧🇩',
    isoCode: 'BD',
    population: 172954319,
    areaSqKm: 147570.0,
    continentName: '아시아',
  },
  {
    name: '멕시코',
    localName: 'México',
    flagEmoji: '🇲🇽',
    isoCode: 'MX',
    population: 128455567,
    areaSqKm: 1964375.0,
    continentName: '북아메리카',
  },
  {
    name: '에티오피아',
    localName: 'ኢትዮጵያ',
    flagEmoji: '🇪🇹',
    isoCode: 'ET',
    population: 126527060,
    areaSqKm: 1104300.0,
    continentName: '아프리카',
  },
  {
    name: '필리핀',
    localName: 'Pilipinas',
    flagEmoji: '🇵🇭',
    isoCode: 'PH',
    population: 117337368,
    areaSqKm: 300000.0,
    continentName: '아시아',
  },
  {
    name: '이집트',
    localName: 'مصر',
    flagEmoji: '🇪🇬',
    isoCode: 'EG',
    population: 112716598,
    areaSqKm: 1002450.0,
    continentName: '아프리카',
  },
  {
    name: '콩고민주공화국',
    localName: 'République démocratique du Congo',
    flagEmoji: '🇨🇩',
    isoCode: 'CD',
    population: 102262808,
    areaSqKm: 2344858.0,
    continentName: '아프리카',
  },
  {
    name: '베트남',
    localName: 'Việt Nam',
    flagEmoji: '🇻🇳',
    isoCode: 'VN',
    population: 98858950,
    areaSqKm: 331212.0,
    continentName: '아시아',
  },
  {
    name: '태국',
    localName: 'ประเทศไทย',
    flagEmoji: '🇹🇭',
    isoCode: 'TH',
    population: 71801279,
    areaSqKm: 513120.0,
    continentName: '아시아',
  },
  {
    name: '탄자니아',
    localName: 'Tanzania',
    flagEmoji: '🇹🇿',
    isoCode: 'TZ',
    population: 67438106,
    areaSqKm: 945087.0,
    continentName: '아프리카',
  },
  {
    name: '남아프리카공화국',
    localName: 'South Africa',
    flagEmoji: '🇿🇦',
    isoCode: 'ZA',
    population: 60414495,
    areaSqKm: 1221037.0,
    continentName: '아프리카',
  },
  {
    name: '이탈리아',
    localName: 'Italia',
    flagEmoji: '🇮🇹',
    isoCode: 'IT',
    population: 58870762,
    areaSqKm: 301340.0,
    continentName: '유럽',
  },
  {
    name: '스페인',
    localName: 'España',
    flagEmoji: '🇪🇸',
    isoCode: 'ES',
    population: 48345223,
    areaSqKm: 505990.0,
    continentName: '유럽',
  },
  {
    name: '포르투갈',
    localName: 'Portugal',
    flagEmoji: '🇵🇹',
    isoCode: 'PT',
    population: 10467366,
    areaSqKm: 92212.0,
    continentName: '유럽',
  },
  {
    name: '케냐',
    localName: 'Kenya',
    flagEmoji: '🇰🇪',
    isoCode: 'KE',
    population: 55100586,
    areaSqKm: 580367.0,
    continentName: '아프리카',
  },
  {
    name: '미얀마',
    localName: 'မြန်မာ',
    flagEmoji: '🇲🇲',
    isoCode: 'MM',
    population: 54577997,
    areaSqKm: 676578.0,
    continentName: '아시아',
  },
  {
    name: '콜롬비아',
    localName: 'Colombia',
    flagEmoji: '🇨🇴',
    isoCode: 'CO',
    population: 52085168,
    areaSqKm: 1141748.0,
    continentName: '남아메리카',
  },
  {
    name: '베네수엘라',
    localName: 'Venezuela',
    flagEmoji: '🇻🇪',
    isoCode: 'VE',
    population: 28838499,
    areaSqKm: 916445.0,
    continentName: '남아메리카',
  },
  {
    name: '수단',
    localName: 'السودان',
    flagEmoji: '🇸🇩',
    isoCode: 'SD',
    population: 48109006,
    areaSqKm: 1861484.0,
    continentName: '아프리카',
  },
  // === 소련 후임 국가 ===
  {
    name: '우크라이나',
    localName: 'Україна',
    flagEmoji: '🇺🇦',
    isoCode: 'UA',
    population: 43531422,
    areaSqKm: 603550.0,
    continentName: '유럽',
  },
  {
    name: '벨라루스',
    localName: 'Беларусь',
    flagEmoji: '🇧🇾',
    isoCode: 'BY',
    population: 9498238,
    areaSqKm: 207600.0,
    continentName: '유럽',
  },
  {
    name: '조지아',
    localName: 'საქართველო',
    flagEmoji: '🇬🇪',
    isoCode: 'GE',
    population: 3744385,
    areaSqKm: 69700.0,
    continentName: '아시아',
  },
  {
    name: '아르메니아',
    localName: 'Հայաստան',
    flagEmoji: '🇦🇲',
    isoCode: 'AM',
    population: 2777970,
    areaSqKm: 29743.0,
    continentName: '아시아',
  },
  {
    name: '아제르바이잔',
    localName: 'Azərbaycan',
    flagEmoji: '🇦🇿',
    isoCode: 'AZ',
    population: 10139177,
    areaSqKm: 86600.0,
    continentName: '아시아',
  },
  {
    name: '카자흐스탄',
    localName: 'Қазақстан',
    flagEmoji: '🇰🇿',
    isoCode: 'KZ',
    population: 19606633,
    areaSqKm: 2724900.0,
    continentName: '아시아',
  },
  {
    name: '우즈베키스탄',
    localName: 'Oʻzbekiston',
    flagEmoji: '🇺🇿',
    isoCode: 'UZ',
    population: 36361643,
    areaSqKm: 448978.0,
    continentName: '아시아',
  },
  {
    name: '투르크메니스탄',
    localName: 'Türkmenistan',
    flagEmoji: '🇹🇲',
    isoCode: 'TM',
    population: 6341855,
    areaSqKm: 488100.0,
    continentName: '아시아',
  },
  {
    name: '타지키스탄',
    localName: 'Тоҷикистон',
    flagEmoji: '🇹🇯',
    isoCode: 'TJ',
    population: 10143543,
    areaSqKm: 143100.0,
    continentName: '아시아',
  },
  {
    name: '키르기스스탄',
    localName: 'Кыргызстан',
    flagEmoji: '🇰🇬',
    isoCode: 'KG',
    population: 7017800,
    areaSqKm: 199951.0,
    continentName: '아시아',
  },
  {
    name: '에스토니아',
    localName: 'Eesti',
    flagEmoji: '🇪🇪',
    isoCode: 'EE',
    population: 1331057,
    areaSqKm: 45228.0,
    continentName: '유럽',
  },
  {
    name: '라트비아',
    localName: 'Latvija',
    flagEmoji: '🇱🇻',
    isoCode: 'LV',
    population: 1830211,
    areaSqKm: 64589.0,
    continentName: '유럽',
  },
  {
    name: '리투아니아',
    localName: 'Lietuva',
    flagEmoji: '🇱🇹',
    isoCode: 'LT',
    population: 2718352,
    areaSqKm: 65300.0,
    continentName: '유럽',
  },
  {
    name: '몰도바',
    localName: 'Moldova',
    flagEmoji: '🇲🇩',
    isoCode: 'MD',
    population: 2512758,
    areaSqKm: 33846.0,
    continentName: '유럽',
  },
]

export async function seedCountries(
  prisma: PrismaService,
  continentMap: Map<string, string>,
): Promise<void> {
  console.log('\n🌏 국가 시딩 시작...')

  for (const country of COUNTRIES) {
    const continentId = continentMap.get(country.continentName)
    if (!continentId) {
      console.error(`  ❌ 대륙을 찾을 수 없음: ${country.continentName}`)
      continue
    }

    const created = await prisma.country.upsert({
      where: { isoCode: country.isoCode },
      update: {
        name: country.name,
        localName: country.localName,
        flagEmoji: country.flagEmoji,
        population: country.population,
        areaSqKm: country.areaSqKm,
        continentId: continentId,
        accountId: ACCOUNT_ID,
        defaultNameDisplayOrder: nameOrderFor(country.isoCode),
      },
      create: {
        name: country.name,
        localName: country.localName,
        flagEmoji: country.flagEmoji,
        isoCode: country.isoCode,
        population: country.population,
        areaSqKm: country.areaSqKm,
        continentId: continentId,
        accountId: ACCOUNT_ID,
        defaultNameDisplayOrder: nameOrderFor(country.isoCode),
      },
    })
    console.log(`  ✅ 국가 생성됨: ${created.name}`)
  }

  console.log(`✅ 총 ${COUNTRIES.length}개 국가 생성 완료!\n`)
}
