/**
 * 일본 자연지리·인프라 시드.
 */
import { PrismaService } from '../prisma.service'
import {
  type InfrastructureSeed,
  type NaturalFeatureSeed,
  seedGeographyForCountry,
} from './geography.shared'

const NATURAL_FEATURES: NaturalFeatureSeed[] = [
  // 산
  {
    type: 'mountain',
    name: '후지산',
    localName: '富士山',
    region: '시즈오카·야마나시',
    latitude: 35.3606,
    longitude: 138.7274,
    heightM: 3776,
    isProtected: true,
  },
  {
    type: 'mountain',
    name: '키타다케',
    localName: '北岳',
    region: '야마나시',
    latitude: 35.6747,
    longitude: 138.2387,
    heightM: 3193,
    isProtected: true,
  },
  {
    type: 'mountain',
    name: '아소산',
    localName: '阿蘇山',
    region: '구마모토',
    latitude: 32.8842,
    longitude: 131.1042,
    heightM: 1592,
    isProtected: true,
  },
  // 강
  {
    type: 'river',
    name: '시나노강',
    localName: '信濃川',
    region: '나가노·니가타',
    latitude: 37.95,
    longitude: 139.05,
    lengthKm: 367,
  },
  {
    type: 'river',
    name: '도네강',
    localName: '利根川',
    region: '간토 평야',
    latitude: 35.74,
    longitude: 140.85,
    lengthKm: 322,
  },
  {
    type: 'river',
    name: '이시카리강',
    localName: '石狩川',
    region: '홋카이도',
    latitude: 43.21,
    longitude: 141.31,
    lengthKm: 268,
  },
  // 호수
  {
    type: 'lake',
    name: '비와호',
    localName: '琵琶湖',
    region: '시가현',
    latitude: 35.25,
    longitude: 136.0833,
    areaSqKm: 670.3,
  },
  {
    type: 'lake',
    name: '카스미가우라',
    localName: '霞ヶ浦',
    region: '이바라키',
    latitude: 36.0,
    longitude: 140.4,
    areaSqKm: 220.0,
  },
  // 해안
  {
    type: 'coast',
    name: '산리쿠 해안',
    localName: '三陸海岸',
    region: '아오모리·이와테·미야기',
    latitude: 39.5,
    longitude: 141.95,
    lengthKm: 600,
    isProtected: true,
  },
  {
    type: 'coast',
    name: '세토 내해',
    localName: '瀬戸内海',
    region: '주고쿠·시코쿠 사이',
    latitude: 34.3,
    longitude: 133.5,
    isProtected: true,
  },
]

const INFRASTRUCTURES: InfrastructureSeed[] = [
  // 고속도로
  {
    type: 'highway',
    name: '도메이 고속도로',
    localName: '東名高速道路',
    code: 'E1',
    region: '도쿄 ↔ 코마키',
    lengthKm: 346.7,
    operatorName: 'NEXCO 중일본·동일본',
    openedYear: 1969,
  },
  {
    type: 'highway',
    name: '도호쿠 자동차도',
    localName: '東北自動車道',
    code: 'E4',
    region: '도쿄 ↔ 아오모리',
    lengthKm: 679.5,
    operatorName: 'NEXCO 동일본',
    openedYear: 1987,
  },
  // 철도
  {
    type: 'railway',
    name: '도카이도 신칸센',
    localName: '東海道新幹線',
    code: 'JR-Tokaido',
    region: '도쿄 ↔ 신오사카',
    lengthKm: 515.4,
    capacity: '연 1.7억명',
    operatorName: 'JR 도카이',
    openedYear: 1964,
  },
  {
    type: 'railway',
    name: '산요 신칸센',
    localName: '山陽新幹線',
    code: 'JR-Sanyo',
    region: '신오사카 ↔ 하카타',
    lengthKm: 622.3,
    operatorName: 'JR 서일본',
    openedYear: 1975,
  },
  {
    type: 'railway',
    name: '도쿄 메트로 마루노우치선',
    localName: '東京メトロ丸ノ内線',
    code: 'M',
    region: '도쿄도 23구',
    lengthKm: 27.4,
    operatorName: '도쿄지하철',
    openedYear: 1954,
  },
  // 공항
  {
    type: 'airport',
    name: '하네다 공항',
    localName: '東京国際空港',
    code: 'HND',
    region: '도쿄도 오타구',
    latitude: 35.5523,
    longitude: 139.7798,
    capacity: '연 8,700만명',
    operatorName: '일본공항빌딩',
    openedYear: 1931,
  },
  {
    type: 'airport',
    name: '나리타 국제공항',
    localName: '成田国際空港',
    code: 'NRT',
    region: '치바현 나리타시',
    latitude: 35.7647,
    longitude: 140.3864,
    capacity: '연 4,400만명',
    operatorName: '나리타국제공항주식회사',
    openedYear: 1978,
  },
  {
    type: 'airport',
    name: '간사이 국제공항',
    localName: '関西国際空港',
    code: 'KIX',
    region: '오사카부 인공섬',
    latitude: 34.4347,
    longitude: 135.244,
    capacity: '연 2,800만명',
    operatorName: '간사이에어포츠',
    openedYear: 1994,
  },
  // 항구
  {
    type: 'port',
    name: '도쿄항',
    localName: '東京港',
    code: 'JPTYO',
    region: '도쿄도',
    latitude: 35.6235,
    longitude: 139.77,
    capacity: '연 4.5M TEU',
    operatorName: '도쿄항만국',
    openedYear: 1941,
  },
  {
    type: 'port',
    name: '요코하마항',
    localName: '横浜港',
    code: 'JPYOK',
    region: '가나가와현 요코하마시',
    latitude: 35.4536,
    longitude: 139.6515,
    capacity: '연 3.0M TEU',
    operatorName: '요코하마항만국',
    openedYear: 1859,
  },
]

export async function seedJapanGeography(prisma: PrismaService): Promise<void> {
  await seedGeographyForCountry(prisma, {
    isoCode: 'JP',
    countryNameKo: '일본',
    naturalFeatures: NATURAL_FEATURES,
    infrastructures: INFRASTRUCTURES,
  })
}
