/**
 * 중국 자연지리·인프라 시드.
 */
import { PrismaService } from '../prisma.service'
import {
  type InfrastructureSeed,
  type NaturalFeatureSeed,
  seedGeographyForCountry,
} from './geography.shared'

const NATURAL_FEATURES: NaturalFeatureSeed[] = [
  // 산
  {
    type: 'mountain',
    name: '에베레스트 (초모랑마)',
    localName: '珠穆朗玛峰',
    region: '시짱(티베트) 자치구·네팔 국경',
    latitude: 27.9881,
    longitude: 86.925,
    heightM: 8849,
    isProtected: true,
  },
  {
    type: 'mountain',
    name: '황산',
    localName: '黄山',
    region: '안후이성',
    latitude: 30.1346,
    longitude: 118.1655,
    heightM: 1864,
    isProtected: true,
  },
  {
    type: 'mountain',
    name: '태산',
    localName: '泰山',
    region: '산둥성',
    latitude: 36.2553,
    longitude: 117.1011,
    heightM: 1545,
    isProtected: true,
  },
  // 강
  {
    type: 'river',
    name: '장강 (양쯔강)',
    localName: '长江',
    region: '칭하이 → 상하이',
    latitude: 31.23,
    longitude: 121.47,
    lengthKm: 6300,
  },
  {
    type: 'river',
    name: '황하',
    localName: '黄河',
    region: '칭하이 → 산둥',
    latitude: 37.46,
    longitude: 119.13,
    lengthKm: 5464,
  },
  {
    type: 'river',
    name: '주강',
    localName: '珠江',
    region: '윈난·구이저우 → 광둥',
    latitude: 22.55,
    longitude: 113.5,
    lengthKm: 2400,
  },
  // 호수
  {
    type: 'lake',
    name: '포양호',
    localName: '鄱阳湖',
    region: '장시성',
    latitude: 29.07,
    longitude: 116.27,
    areaSqKm: 3960.0,
  },
  {
    type: 'lake',
    name: '동정호',
    localName: '洞庭湖',
    region: '후난성',
    latitude: 29.32,
    longitude: 112.95,
    areaSqKm: 2820.0,
  },
  {
    type: 'lake',
    name: '칭하이 호',
    localName: '青海湖',
    region: '칭하이성',
    latitude: 36.92,
    longitude: 100.13,
    areaSqKm: 4317.0,
  },
  // 해안
  {
    type: 'coast',
    name: '발해 연안',
    localName: '渤海沿岸',
    region: '랴오닝·허베이·산둥',
    latitude: 38.5,
    longitude: 119.5,
    lengthKm: 3784,
  },
  {
    type: 'coast',
    name: '동중국해 연안',
    localName: '东海沿岸',
    region: '저장·푸젠·상하이',
    latitude: 28.5,
    longitude: 121.5,
    lengthKm: 4000,
  },
]

const INFRASTRUCTURES: InfrastructureSeed[] = [
  // 고속도로
  {
    type: 'highway',
    name: '징강아오 고속도로',
    localName: '京港澳高速公路',
    code: 'G4',
    region: '베이징 ↔ 홍콩·마카오',
    lengthKm: 2285,
    operatorName: '교통운수부',
    openedYear: 2000,
  },
  {
    type: 'highway',
    name: '롄훠 고속도로',
    localName: '连霍高速公路',
    code: 'G30',
    region: '롄윈강 ↔ 호르고스',
    lengthKm: 4395,
    operatorName: '교통운수부',
    openedYear: 1998,
  },
  // 철도
  {
    type: 'railway',
    name: '징후 고속철도',
    localName: '京沪高速铁路',
    code: 'CRH-Beijing-Shanghai',
    region: '베이징 ↔ 상하이',
    lengthKm: 1318,
    capacity: '연 2.1억명',
    operatorName: '국가철도그룹',
    openedYear: 2011,
  },
  {
    type: 'railway',
    name: '광선강 고속철도',
    localName: '广深港高速铁路',
    code: 'XRL',
    region: '광저우 ↔ 홍콩',
    lengthKm: 142,
    operatorName: '국가철도그룹·MTR',
    openedYear: 2018,
  },
  {
    type: 'railway',
    name: '베이징 지하철',
    localName: '北京地铁',
    code: 'BJSubway',
    region: '베이징시',
    lengthKm: 836,
    capacity: '연 39억명',
    operatorName: '베이징지하철운영',
    openedYear: 1971,
  },
  // 공항
  {
    type: 'airport',
    name: '베이징 다싱 국제공항',
    localName: '北京大兴国际机场',
    code: 'PKX',
    region: '베이징시·랑팡',
    latitude: 39.5099,
    longitude: 116.4108,
    capacity: '연 7,200만명',
    operatorName: '베이징수도공항그룹',
    openedYear: 2019,
  },
  {
    type: 'airport',
    name: '상하이 푸둥 국제공항',
    localName: '上海浦东国际机场',
    code: 'PVG',
    region: '상하이시 푸둥구',
    latitude: 31.1443,
    longitude: 121.8083,
    capacity: '연 7,600만명',
    operatorName: '상하이공항그룹',
    openedYear: 1999,
  },
  {
    type: 'airport',
    name: '광저우 바이윈 국제공항',
    localName: '广州白云国际机场',
    code: 'CAN',
    region: '광둥성 광저우',
    latitude: 23.3924,
    longitude: 113.299,
    capacity: '연 7,400만명',
    operatorName: '광동공항관리그룹',
    openedYear: 1933,
  },
  // 항구
  {
    type: 'port',
    name: '상하이항',
    localName: '上海港',
    code: 'CNSHA',
    region: '상하이시',
    latitude: 31.224,
    longitude: 121.49,
    capacity: '연 47M TEU (세계 1위)',
    operatorName: '상하이국제항그룹',
    openedYear: 1842,
  },
  {
    type: 'port',
    name: '닝보-저우산항',
    localName: '宁波舟山港',
    code: 'CNNGB',
    region: '저장성 닝보·저우산',
    latitude: 29.87,
    longitude: 121.53,
    capacity: '연 33M TEU',
    operatorName: '닝보저우산항그룹',
    openedYear: 1973,
  },
  {
    type: 'port',
    name: '선전항',
    localName: '深圳港',
    code: 'CNSZN',
    region: '광둥성 선전',
    latitude: 22.5,
    longitude: 113.95,
    capacity: '연 28M TEU',
    operatorName: '선전항만그룹',
    openedYear: 1980,
  },
]

export async function seedChinaGeography(prisma: PrismaService): Promise<void> {
  await seedGeographyForCountry(prisma, {
    isoCode: 'CN',
    countryNameKo: '중국',
    naturalFeatures: NATURAL_FEATURES,
    infrastructures: INFRASTRUCTURES,
  })
}
