/**
 * 미국 자연지리·인프라 시드.
 */
import { PrismaService } from '../prisma.service'
import {
  type InfrastructureSeed,
  type NaturalFeatureSeed,
  seedGeographyForCountry,
} from './geography.shared'

const NATURAL_FEATURES: NaturalFeatureSeed[] = [
  // 산
  {
    type: 'mountain',
    name: '데날리',
    localName: 'Denali',
    region: '알래스카',
    latitude: 63.0692,
    longitude: -151.0067,
    heightM: 6190,
    isProtected: true,
  },
  {
    type: 'mountain',
    name: '휘트니산',
    localName: 'Mount Whitney',
    region: '캘리포니아',
    latitude: 36.5786,
    longitude: -118.2922,
    heightM: 4421,
    isProtected: true,
  },
  {
    type: 'mountain',
    name: '레이니어산',
    localName: 'Mount Rainier',
    region: '워싱턴',
    latitude: 46.8523,
    longitude: -121.7603,
    heightM: 4392,
    isProtected: true,
  },
  // 강
  {
    type: 'river',
    name: '미시시피강',
    localName: 'Mississippi River',
    region: '미네소타 → 멕시코만',
    latitude: 32.3,
    longitude: -90.9,
    lengthKm: 3766,
  },
  {
    type: 'river',
    name: '미주리강',
    localName: 'Missouri River',
    region: '몬태나 → 미주리',
    latitude: 38.8,
    longitude: -90.18,
    lengthKm: 3767,
  },
  {
    type: 'river',
    name: '콜로라도강',
    localName: 'Colorado River',
    region: '콜로라도 → 캘리포니아',
    latitude: 36.0544,
    longitude: -112.1401,
    lengthKm: 2330,
  },
  // 호수
  {
    type: 'lake',
    name: '슈피리어 호',
    localName: 'Lake Superior',
    region: '미네소타·위스콘신·미시간',
    latitude: 47.7,
    longitude: -87.5,
    areaSqKm: 82100.0,
  },
  {
    type: 'lake',
    name: '미시간 호',
    localName: 'Lake Michigan',
    region: '미시간·일리노이·인디애나·위스콘신',
    latitude: 43.5,
    longitude: -87.0,
    areaSqKm: 58000.0,
  },
  {
    type: 'lake',
    name: '그레이트솔트 호',
    localName: 'Great Salt Lake',
    region: '유타',
    latitude: 41.1,
    longitude: -112.4,
    areaSqKm: 4400.0,
  },
  // 해안
  {
    type: 'coast',
    name: '동부 해안',
    localName: 'East Coast (Atlantic)',
    region: '메인 ↔ 플로리다',
    latitude: 38.0,
    longitude: -76.0,
    lengthKm: 3500,
  },
  {
    type: 'coast',
    name: '서부 해안',
    localName: 'West Coast (Pacific)',
    region: '워싱턴 ↔ 캘리포니아',
    latitude: 38.0,
    longitude: -123.0,
    lengthKm: 2030,
  },
  {
    type: 'coast',
    name: '걸프 해안',
    localName: 'Gulf Coast',
    region: '텍사스 ↔ 플로리다',
    latitude: 29.5,
    longitude: -90.0,
    lengthKm: 2625,
  },
]

const INFRASTRUCTURES: InfrastructureSeed[] = [
  // 고속도로
  {
    type: 'highway',
    name: 'I-95 (인터스테이트 95)',
    localName: 'Interstate 95',
    code: 'I-95',
    region: '메인 ↔ 플로리다',
    lengthKm: 3084,
    operatorName: '주별 교통국 (FHWA)',
    openedYear: 1957,
  },
  {
    type: 'highway',
    name: 'I-90 (인터스테이트 90)',
    localName: 'Interstate 90',
    code: 'I-90',
    region: '시애틀 ↔ 보스턴',
    lengthKm: 4860,
    operatorName: '주별 교통국 (FHWA)',
    openedYear: 1957,
  },
  // 철도
  {
    type: 'railway',
    name: '암트랙 노스이스트 코리도',
    localName: 'Amtrak Northeast Corridor',
    code: 'NEC',
    region: '보스턴 ↔ 워싱턴 D.C.',
    lengthKm: 735,
    capacity: '연 1.2억명',
    operatorName: 'Amtrak',
    openedYear: 1976,
  },
  {
    type: 'railway',
    name: '뉴욕 지하철',
    localName: 'New York City Subway',
    code: 'MTA',
    region: '뉴욕시',
    lengthKm: 380,
    capacity: '연 17억명',
    operatorName: 'MTA',
    openedYear: 1904,
  },
  // 공항
  {
    type: 'airport',
    name: '하츠필드-잭슨 애틀랜타 공항',
    localName: 'Hartsfield-Jackson Atlanta International Airport',
    code: 'ATL',
    region: '조지아주 애틀랜타',
    latitude: 33.6407,
    longitude: -84.4277,
    capacity: '연 1억 800만명',
    operatorName: '애틀랜타시',
    openedYear: 1925,
  },
  {
    type: 'airport',
    name: '로스앤젤레스 국제공항',
    localName: 'Los Angeles International Airport',
    code: 'LAX',
    region: '캘리포니아주 로스앤젤레스',
    latitude: 33.9425,
    longitude: -118.4081,
    capacity: '연 8,800만명',
    operatorName: 'Los Angeles World Airports',
    openedYear: 1930,
  },
  {
    type: 'airport',
    name: '존 F. 케네디 국제공항',
    localName: 'John F. Kennedy International Airport',
    code: 'JFK',
    region: '뉴욕주 퀸스',
    latitude: 40.6413,
    longitude: -73.7781,
    capacity: '연 6,200만명',
    operatorName: '뉴욕·뉴저지 항만청',
    openedYear: 1948,
  },
  // 항구
  {
    type: 'port',
    name: '로스앤젤레스 항',
    localName: 'Port of Los Angeles',
    code: 'USLAX',
    region: '캘리포니아주 산페드로',
    latitude: 33.74,
    longitude: -118.27,
    capacity: '연 9.9M TEU',
    operatorName: '로스앤젤레스 항만국',
    openedYear: 1907,
  },
  {
    type: 'port',
    name: '뉴욕·뉴저지 항',
    localName: 'Port of New York and New Jersey',
    code: 'USNYC',
    region: '뉴욕·뉴저지',
    latitude: 40.668,
    longitude: -74.155,
    capacity: '연 9.5M TEU',
    operatorName: '뉴욕·뉴저지 항만청',
    openedYear: 1921,
  },
]

export async function seedUsaGeography(prisma: PrismaService): Promise<void> {
  await seedGeographyForCountry(prisma, {
    isoCode: 'US',
    countryNameKo: '미국',
    naturalFeatures: NATURAL_FEATURES,
    infrastructures: INFRASTRUCTURES,
  })
}
