/**
 * @packageDocumentation
 * @module api.functional.events.parent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { EventResponseDto } from "../../../../libs/event/presentation/dto";

/**
 * 상위 사건의 하위 사건 목록 조회
 *
 * @param parentEventId 상위 사건 ID
 * @returns 하위 사건 목록
 * @tag events
 *
 * @controller EventController.getEventsByParentId
 * @path GET /events/parent/:parentEventId
 * @accessor api.functional.events.parent.getEventsByParentId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getEventsByParentId(
  connection: IConnection,
  parentEventId: string,
): Promise<getEventsByParentId.Output> {
  return PlainFetcher.fetch(connection, {
    ...getEventsByParentId.METADATA,
    template: getEventsByParentId.METADATA.path,
    path: getEventsByParentId.path(parentEventId),
  });
}
export namespace getEventsByParentId {
  export type Output = Primitive<Array<EventResponseDto>>;

  export const METADATA = {
    method: "GET",
    path: "/events/parent/:parentEventId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (parentEventId: string) =>
    `/events/parent/${encodeURIComponent(parentEventId?.toString() ?? "null")}`;
}
