-- AlterTable
ALTER TABLE `person` ADD COLUMN `death_cause` VARCHAR(300) NULL,
    ADD COLUMN `death_note` TEXT NULL,
    ADD COLUMN `death_type` ENUM('NATURAL', 'ILLNESS', 'ASSASSINATION', 'EXECUTION', 'BATTLE', 'ACCIDENT', 'SUICIDE', 'UNKNOWN', 'OTHER') NULL;