#!/usr/bin/env node
declare const USAGE = "Wrong command has been detected. Use like below:\n\nnpx nestia [command] [options?]\n\n  1. npx nestia start <directory>\n  2. npx nestia template <directory>\n  3. npx nestia setup\n  4. npx nestia dependencies\n  5. npx nestia init\n  6. npx nestia sdk\n  7. npx nestia swagger\n  9. npx nestia e2e\n  10. npx nestia all\n";
declare function halt(desc: string): never;
declare function main(): Promise<void>;
