/**
 * @packageDocumentation
 * @module api.functional.users.me.password
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { ChangePasswordDto } from "../../../../../libs/user/presentation/dto/user.dto";

/**
 * 비밀번호 변경
 * @controller UserController.changePassword
 * @path PUT /users/me/password
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function changePassword(
  connection: IConnection,
  dto: changePassword.Body,
): Promise<changePassword.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...changePassword.METADATA,
      template: changePassword.METADATA.path,
      path: changePassword.path(),
    },
    dto,
  );
}
export namespace changePassword {
  export type Body = Primitive<ChangePasswordDto>;
  export type Output = Primitive<{ message: string }>;

  export const METADATA = {
    method: "PUT",
    path: "/users/me/password",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/users/me/password";
}
