/**
 * @packageDocumentation
 * @module api.functional.curations.item
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { AggregateType } from '@prisma/client';
import type { Primitive } from "typia";

import type { PaginatedCurationResponse } from "../../../../libs/curation/presentation/curation.controller";

/**
 * @controller CurationController.getItemFeed
 * @path GET /curations/item/:itemType/:itemId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getItemFeed(
  connection: IConnection,
  itemType: AggregateType,
  itemId: string,
  page: string,
  pageSize: string,
): Promise<getItemFeed.Output> {
  return PlainFetcher.fetch(connection, {
    ...getItemFeed.METADATA,
    template: getItemFeed.METADATA.path,
    path: getItemFeed.path(itemType, itemId, page, pageSize),
  });
}
export namespace getItemFeed {
  export type Output = Primitive<PaginatedCurationResponse>;

  export const METADATA = {
    method: "GET",
    path: "/curations/item/:itemType/:itemId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    itemType: AggregateType,
    itemId: string,
    page: string,
    pageSize: string,
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      page: page,
      pageSize: pageSize,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/curations/item/${encodeURIComponent(itemType?.toString() ?? "null")}/${encodeURIComponent(itemId?.toString() ?? "null")}`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
