/**
 * @packageDocumentation
 * @module api.functional.users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  UserResponseDto,
  UsersResponseDto,
} from "../../../libs/user/presentation/dto/user-response.dto";
import type {
  LoginDto,
  RegisterDto,
} from "../../../libs/user/presentation/dto/user.dto";

export * as me from "./me";
export * as by_name from "./by_name";

/**
 * 회원가입
 * @controller UserController.register
 * @path POST /users/register
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function register(
  connection: IConnection,
  dto: register.Body,
): Promise<register.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...register.METADATA,
      template: register.METADATA.path,
      path: register.path(),
    },
    dto,
  );
}
export namespace register {
  export type Body = Primitive<RegisterDto>;
  export type Output = Primitive<UserResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/users/register",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/users/register";
}

/**
 * 로그인
 * @controller UserController.login
 * @path POST /users/login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  dto: login.Body,
): Promise<login.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...login.METADATA,
      template: login.METADATA.path,
      path: login.path(),
    },
    dto,
  );
}
export namespace login {
  export type Body = Primitive<LoginDto>;
  export type Output = Primitive<{
    user: UserResponseDto;
    accessToken: string;
  }>;

  export const METADATA = {
    method: "POST",
    path: "/users/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/users/login";
}

/**
 * 사용자 조회 (ID)
 * @controller UserController.findById
 * @path GET /users/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findById(
  connection: IConnection,
  id: string,
): Promise<findById.Output> {
  return PlainFetcher.fetch(connection, {
    ...findById.METADATA,
    template: findById.METADATA.path,
    path: findById.path(id),
  });
}
export namespace findById {
  export type Output = Primitive<UserResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/users/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/users/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 사용자 목록 조회
 * @controller UserController.findMany
 * @path GET /users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findMany(
  connection: IConnection,
  page: string,
  pageSize: string,
  orderBy: "createdAt" | "followerCount",
  order: "asc" | "desc",
): Promise<findMany.Output> {
  return PlainFetcher.fetch(connection, {
    ...findMany.METADATA,
    template: findMany.METADATA.path,
    path: findMany.path(page, pageSize, orderBy, order),
  });
}
export namespace findMany {
  export type Output = Primitive<UsersResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/users",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    page: string,
    pageSize: string,
    orderBy: "createdAt" | "followerCount",
    order: "asc" | "desc",
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      page: page,
      pageSize: pageSize,
      orderBy: orderBy,
      order: order,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/users";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
