-- AlterTable
ALTER TABLE `government_position_definition` MODIFY `position_type` ENUM('HEAD_OF_STATE', 'HEAD_OF_GOVERNMENT', 'DEPUTY_HEAD_OF_STATE', 'HEIR_APPARENT', 'REGENT', 'CABINET_MINISTER', 'VICE_MINISTER', 'LEGISLATOR', 'JUDICIARY', 'LOCAL_GOVERNMENT', 'SPECIAL_POSITION', 'MILITARY_COMMANDER', 'ROYAL_NOBLE_TITLE', 'OTHER') NOT NULL;

-- AlterTable
ALTER TABLE `government_position_tenure` MODIFY `position_type` ENUM('HEAD_OF_STATE', 'HEAD_OF_GOVERNMENT', 'DEPUTY_HEAD_OF_STATE', 'HEIR_APPARENT', 'REGENT', 'CABINET_MINISTER', 'VICE_MINISTER', 'LEGISLATOR', 'JUDICIARY', 'LOCAL_GOVERNMENT', 'SPECIAL_POSITION', 'MILITARY_COMMANDER', 'ROYAL_NOBLE_TITLE', 'OTHER') NOT NULL;
