/**
 * @packageDocumentation
 * @module api.functional.countries.historical_countries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * 현대 국가와 연결된 역사적 국가 목록 조회
 *
 * @param id 현대 국가 ID
 * @returns 역사적 국가 목록
 * @tag countries
 *
 * @controller CountryController.getHistoricalCountriesByModernCountryId
 * @path GET /countries/:id/historical-countries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHistoricalCountriesByModernCountryId(
  connection: IConnection,
  id: string,
): Promise<getHistoricalCountriesByModernCountryId.Output> {
  return PlainFetcher.fetch(connection, {
    ...getHistoricalCountriesByModernCountryId.METADATA,
    template: getHistoricalCountriesByModernCountryId.METADATA.path,
    path: getHistoricalCountriesByModernCountryId.path(id),
  });
}
export namespace getHistoricalCountriesByModernCountryId {
  export type Output = Primitive<
    {
      id: string;
      name: string;
      enName: string | null;
      thumbnailUrl: string | null;
      stateType: string;
      startEra: "BC" | "AD" | null;
      startYear: number | null;
      startMonth: number | null;
      startDay: number | null;
      endEra: "BC" | "AD" | null;
      endYear: number | null;
      endMonth: number | null;
      endDay: number | null;
    }[]
  >;

  export const METADATA = {
    method: "GET",
    path: "/countries/:id/historical-countries",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/countries/${encodeURIComponent(id?.toString() ?? "null")}/historical-countries`;
}
