/**
 * @packageDocumentation
 * @module api.functional.countries.development_indicators
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";

import type { DevelopmentIndicatorResponse } from '../../../../libs/country/presentation/dto'

/**
 * 국가별 발전 지표 조회
 *
 * @param id 국가 ID
 * @param query 쿼리 파라미터
 * @returns 발전 지표 목록
 * @tag countries
 *
 * @controller CountryController.getDevelopmentIndicators
 * @path GET /countries/:id/development-indicators
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getDevelopmentIndicators(
  connection: IConnection,
  id: string,
  query: getDevelopmentIndicators.Query,
): Promise<getDevelopmentIndicators.Output> {
  return PlainFetcher.fetch(connection, {
    ...getDevelopmentIndicators.METADATA,
    template: getDevelopmentIndicators.METADATA.path,
    path: getDevelopmentIndicators.path(id, query),
  });
}
export namespace getDevelopmentIndicators {
  export type Query = Resolved<{
    startYear?: string;
    endYear?: string;
  }>;
  export type Output = Primitive<DevelopmentIndicatorResponse[]>;

  export const METADATA = {
    method: "GET",
    path: "/countries/:id/development-indicators",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string, query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/countries/${encodeURIComponent(id?.toString() ?? "null")}/development-indicators`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
