/**
 * @packageDocumentation
 * @module api.functional.countries.development_indicators
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";

import type {
  DevelopmentIndicatorResponse,
  UpsertDevelopmentIndicatorDto,
} from "../../../../libs/country/presentation/dto";

/**
 * 국가별 발전 지표 조회
 *
 * @param id 국가 ID
 * @param query 쿼리 파라미터
 * @returns 발전 지표 목록
 * @tag countries
 *
 * @controller CountryController.getDevelopmentIndicators
 * @path GET /countries/:id/development-indicators
 * @accessor api.functional.countries.development_indicators.getDevelopmentIndicators
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getDevelopmentIndicators(
  connection: IConnection,
  id: string,
  query: getDevelopmentIndicators.Query,
): Promise<getDevelopmentIndicators.Output> {
  return PlainFetcher.fetch(connection, {
    ...getDevelopmentIndicators.METADATA,
    template: getDevelopmentIndicators.METADATA.path,
    path: getDevelopmentIndicators.path(id, query),
  });
}
export namespace getDevelopmentIndicators {
  export type Query = Resolved<{
    startYear?: string;
    endYear?: string;
  }>;
  export type Output = Primitive<Array<DevelopmentIndicatorResponse>>;

  export const METADATA = {
    method: "GET",
    path: "/countries/:id/development-indicators",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string, query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/countries/${encodeURIComponent(id?.toString() ?? "null")}/development-indicators`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * 발전 지표 생성/갱신 (countryId+year 기준 upsert)
 *
 * @tag countries
 *
 * @controller CountryController.upsertDevelopmentIndicator
 * @path POST /countries/:id/development-indicators
 * @accessor api.functional.countries.development_indicators.upsertDevelopmentIndicator
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function upsertDevelopmentIndicator(
  connection: IConnection,
  id: string,
  dto: upsertDevelopmentIndicator.Body,
): Promise<upsertDevelopmentIndicator.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...upsertDevelopmentIndicator.METADATA,
      template: upsertDevelopmentIndicator.METADATA.path,
      path: upsertDevelopmentIndicator.path(id),
    },
    dto,
  );
}
export namespace upsertDevelopmentIndicator {
  export type Body = Primitive<UpsertDevelopmentIndicatorDto>;
  export type Output = Primitive<DevelopmentIndicatorResponse>;

  export const METADATA = {
    method: "POST",
    path: "/countries/:id/development-indicators",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string) =>
    `/countries/${encodeURIComponent(id?.toString() ?? "null")}/development-indicators`;
}

/**
 * 발전 지표 삭제 (해당 연도)
 *
 * @tag countries
 *
 * @controller CountryController.deleteDevelopmentIndicator
 * @path DELETE /countries/:id/development-indicators/:year
 * @accessor api.functional.countries.development_indicators.deleteDevelopmentIndicator
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteDevelopmentIndicator(
  connection: IConnection,
  id: string,
  year: number,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteDevelopmentIndicator.METADATA,
    template: deleteDevelopmentIndicator.METADATA.path,
    path: deleteDevelopmentIndicator.path(id, year),
  });
}
export namespace deleteDevelopmentIndicator {
  export const METADATA = {
    method: "DELETE",
    path: "/countries/:id/development-indicators/:year",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string, year: number) =>
    `/countries/${encodeURIComponent(id?.toString() ?? "null")}/development-indicators/${encodeURIComponent(year?.toString() ?? "null")}`;
}
