-- AlterTable
ALTER TABLE `company_history` ADD COLUMN `currency` VARCHAR(10) NULL,
    ADD COLUMN `market_cap` DECIMAL(24, 2) NULL,
    ADD COLUMN `stock_price` DECIMAL(20, 4) NULL,
    ADD COLUMN `type` ENUM('GENERAL', 'PRODUCT_LAUNCH', 'FINANCIAL', 'MERGER_ACQUISITION', 'LEADERSHIP', 'LEGAL', 'MILESTONE', 'OTHER') NULL DEFAULT 'GENERAL';
