/**
 * @packageDocumentation
 * @module api.functional.countries.economic_indicators
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";

import type {
  EconomicIndicatorResponse,
  UpsertEconomicIndicatorDto,
} from "../../../../libs/country/presentation/dto";

/**
 * 국가별 경제 지표 조회
 *
 * @param id 국가 ID
 * @param query 쿼리 파라미터
 * @returns 경제 지표 목록
 * @tag countries
 *
 * @controller CountryController.getEconomicIndicators
 * @path GET /countries/:id/economic-indicators
 * @accessor api.functional.countries.economic_indicators.getEconomicIndicators
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getEconomicIndicators(
  connection: IConnection,
  id: string,
  query: getEconomicIndicators.Query,
): Promise<getEconomicIndicators.Output> {
  return PlainFetcher.fetch(connection, {
    ...getEconomicIndicators.METADATA,
    template: getEconomicIndicators.METADATA.path,
    path: getEconomicIndicators.path(id, query),
  });
}
export namespace getEconomicIndicators {
  export type Query = Resolved<{
    startYear?: string;
    endYear?: string;
  }>;
  export type Output = Primitive<Array<EconomicIndicatorResponse>>;

  export const METADATA = {
    method: "GET",
    path: "/countries/:id/economic-indicators",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string, query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/countries/${encodeURIComponent(id?.toString() ?? "null")}/economic-indicators`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * 경제 지표 생성/갱신 (countryId+year 기준 upsert)
 *
 * @tag countries
 *
 * @controller CountryController.upsertEconomicIndicator
 * @path POST /countries/:id/economic-indicators
 * @accessor api.functional.countries.economic_indicators.upsertEconomicIndicator
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function upsertEconomicIndicator(
  connection: IConnection,
  id: string,
  dto: upsertEconomicIndicator.Body,
): Promise<upsertEconomicIndicator.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...upsertEconomicIndicator.METADATA,
      template: upsertEconomicIndicator.METADATA.path,
      path: upsertEconomicIndicator.path(id),
    },
    dto,
  );
}
export namespace upsertEconomicIndicator {
  export type Body = Primitive<UpsertEconomicIndicatorDto>;
  export type Output = Primitive<EconomicIndicatorResponse>;

  export const METADATA = {
    method: "POST",
    path: "/countries/:id/economic-indicators",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string) =>
    `/countries/${encodeURIComponent(id?.toString() ?? "null")}/economic-indicators`;
}

/**
 * 경제 지표 삭제 (해당 연도)
 *
 * @tag countries
 *
 * @controller CountryController.deleteEconomicIndicator
 * @path DELETE /countries/:id/economic-indicators/:year
 * @accessor api.functional.countries.economic_indicators.deleteEconomicIndicator
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteEconomicIndicator(
  connection: IConnection,
  id: string,
  year: number,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteEconomicIndicator.METADATA,
    template: deleteEconomicIndicator.METADATA.path,
    path: deleteEconomicIndicator.path(id, year),
  });
}
export namespace deleteEconomicIndicator {
  export const METADATA = {
    method: "DELETE",
    path: "/countries/:id/economic-indicators/:year",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string, year: number) =>
    `/countries/${encodeURIComponent(id?.toString() ?? "null")}/economic-indicators/${encodeURIComponent(year?.toString() ?? "null")}`;
}
