/**
 * @packageDocumentation
 * @module api.functional.social.liked
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { BooleanResponse } from "../../../../libs/social/presentation/social.controller";

/**
 * @controller SocialController.isLiked
 * @path GET /social/liked/:curationId
 * @accessor api.functional.social.liked.isLiked
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function isLiked(
  connection: IConnection,
  curationId: string,
): Promise<isLiked.Output> {
  return PlainFetcher.fetch(connection, {
    ...isLiked.METADATA,
    template: isLiked.METADATA.path,
    path: isLiked.path(curationId),
  });
}
export namespace isLiked {
  export type Output = Primitive<BooleanResponse>;

  export const METADATA = {
    method: "GET",
    path: "/social/liked/:curationId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (curationId: string) =>
    `/social/liked/${encodeURIComponent(curationId?.toString() ?? "null")}`;
}
