/**
 * @packageDocumentation
 * @module api.functional.curations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreateCurationDto,
  UpdateCurationDto,
} from "../../../libs/curation/application/curation.service";
import type {
  MessageResponse,
  ReportCurationDto,
} from "../../../libs/curation/presentation/curation.controller";

export * as item from "./item";
export * as user from "./user";

/**
 * @controller CurationController.create
 * @path POST /curations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  dto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    dto,
  );
}
export namespace create {
  export type Body = Primitive<CreateCurationDto>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "POST",
    path: "/curations",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/curations";
}

/**
 * @controller CurationController.findById
 * @path GET /curations/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findById(
  connection: IConnection,
  id: string,
): Promise<findById.Output> {
  return PlainFetcher.fetch(connection, {
    ...findById.METADATA,
    template: findById.METADATA.path,
    path: findById.path(id),
  });
}
export namespace findById {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "GET",
    path: "/curations/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/curations/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller CurationController.update
 * @path PUT /curations/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  dto: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    dto,
  );
}
export namespace update {
  export type Body = Primitive<UpdateCurationDto>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "PUT",
    path: "/curations/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/curations/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller CurationController.publish
 * @path POST /curations/:id/publish
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function publish(
  connection: IConnection,
  id: string,
): Promise<publish.Output> {
  return PlainFetcher.fetch(connection, {
    ...publish.METADATA,
    template: publish.METADATA.path,
    path: publish.path(id),
  });
}
export namespace publish {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "POST",
    path: "/curations/:id/publish",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string) =>
    `/curations/${encodeURIComponent(id?.toString() ?? "null")}/publish`;
}

/**
 * @controller CurationController.$delete
 * @path DELETE /curations/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function $delete(
  connection: IConnection,
  id: string,
): Promise<$delete.Output> {
  return PlainFetcher.fetch(connection, {
    ...$delete.METADATA,
    template: $delete.METADATA.path,
    path: $delete.path(id),
  });
}
export namespace $delete {
  export type Output = Primitive<MessageResponse>;

  export const METADATA = {
    method: "DELETE",
    path: "/curations/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/curations/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller CurationController.verify
 * @path POST /curations/:id/verify
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function verify(
  connection: IConnection,
  id: string,
): Promise<verify.Output> {
  return PlainFetcher.fetch(connection, {
    ...verify.METADATA,
    template: verify.METADATA.path,
    path: verify.path(id),
  });
}
export namespace verify {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "POST",
    path: "/curations/:id/verify",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string) =>
    `/curations/${encodeURIComponent(id?.toString() ?? "null")}/verify`;
}

/**
 * @controller CurationController.report
 * @path POST /curations/:id/report
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function report(
  connection: IConnection,
  id: string,
  dto: report.Body,
): Promise<report.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...report.METADATA,
      template: report.METADATA.path,
      path: report.path(id),
    },
    dto,
  );
}
export namespace report {
  export type Body = Primitive<ReportCurationDto>;
  export type Output = Primitive<MessageResponse>;

  export const METADATA = {
    method: "POST",
    path: "/curations/:id/report",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string) =>
    `/curations/${encodeURIComponent(id?.toString() ?? "null")}/report`;
}
