/**
 * @packageDocumentation
 * @module api.functional.curations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreateCurationDto,
  UpdateCurationDto,
} from "../../../libs/curation/application/curation.service";
import type { MessageResponse } from "../../../libs/curation/presentation/curation.controller";

export * as user from "./user/index";

/**
 * @controller CurationController.create
 * @path POST /posts
 * @accessor api.functional.curations.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  dto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    dto,
  );
}
export namespace create {
  export type Body = Primitive<CreateCurationDto>;
  export type Output = Primitive<Array<any>>;

  export const METADATA = {
    method: "POST",
    path: "/posts",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/posts";
}

/**
 * @controller CurationController.findById
 * @path GET /posts/:id
 * @accessor api.functional.curations.findById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findById(
  connection: IConnection,
  id: string,
): Promise<findById.Output> {
  return PlainFetcher.fetch(connection, {
    ...findById.METADATA,
    template: findById.METADATA.path,
    path: findById.path(id),
  });
}
export namespace findById {
  export type Output = Primitive<Array<any>>;

  export const METADATA = {
    method: "GET",
    path: "/posts/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/posts/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller CurationController.update
 * @path PUT /posts/:id
 * @accessor api.functional.curations.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  dto: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    dto,
  );
}
export namespace update {
  export type Body = Primitive<UpdateCurationDto>;
  export type Output = Primitive<Array<any>>;

  export const METADATA = {
    method: "PUT",
    path: "/posts/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/posts/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller CurationController.publish
 * @path POST /posts/:id/publish
 * @accessor api.functional.curations.publish
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function publish(
  connection: IConnection,
  id: string,
): Promise<publish.Output> {
  return PlainFetcher.fetch(connection, {
    ...publish.METADATA,
    template: publish.METADATA.path,
    path: publish.path(id),
  });
}
export namespace publish {
  export type Output = Primitive<Array<any>>;

  export const METADATA = {
    method: "POST",
    path: "/posts/:id/publish",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string) =>
    `/posts/${encodeURIComponent(id?.toString() ?? "null")}/publish`;
}

/**
 * @controller CurationController._delete
 * @path DELETE /posts/:id
 * @accessor api.functional.curations._delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function _delete(
  connection: IConnection,
  id: string,
): Promise<_delete.Output> {
  return PlainFetcher.fetch(connection, {
    ..._delete.METADATA,
    template: _delete.METADATA.path,
    path: _delete.path(id),
  });
}
export namespace _delete {
  export type Output = Primitive<MessageResponse>;

  export const METADATA = {
    method: "DELETE",
    path: "/posts/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/posts/${encodeURIComponent(id?.toString() ?? "null")}`;
}
