/**
 * @packageDocumentation
 * @module api.functional.countries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { CountryResponseDto } from "../../../libs/country/presentation/dto";
import type { CreateCountryDto } from "../../../libs/country/presentation/dto/create-country.dto";
import type { UpdateCountryDto } from "../../../libs/country/presentation/dto/update-country.dto";

export * as historical_countries from "./historical_countries";

/**
 * 모든 국가 조회
 *
 * @returns 국가 목록
 * @tag countries
 *
 * @controller CountryController.getAllCountries
 * @path GET /countries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllCountries(
  connection: IConnection,
): Promise<getAllCountries.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAllCountries.METADATA,
    template: getAllCountries.METADATA.path,
    path: getAllCountries.path(),
  });
}
export namespace getAllCountries {
  export type Output = Primitive<CountryResponseDto[]>;

  export const METADATA = {
    method: "GET",
    path: "/countries",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/countries";
}

/**
 * 국가 상세 조회
 *
 * @param id 국가 ID
 * @returns 국가 정보
 * @tag countries
 *
 * @controller CountryController.getCountryById
 * @path GET /countries/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getCountryById(
  connection: IConnection,
  id: string,
): Promise<getCountryById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getCountryById.METADATA,
    template: getCountryById.METADATA.path,
    path: getCountryById.path(id),
  });
}
export namespace getCountryById {
  export type Output = Primitive<CountryResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/countries/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/countries/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 국가 생성
 *
 * @param dto 국가 생성 정보
 * @returns 생성된 국가
 * @tag countries
 *
 * @controller CountryController.createCountry
 * @path POST /countries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createCountry(
  connection: IConnection,
  dto: createCountry.Body,
): Promise<createCountry.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createCountry.METADATA,
      template: createCountry.METADATA.path,
      path: createCountry.path(),
    },
    dto,
  );
}
export namespace createCountry {
  export type Body = Primitive<CreateCountryDto>;
  export type Output = Primitive<CountryResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/countries",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/countries";
}

/**
 * 국가 수정
 *
 * @param id 국가 ID
 * @param dto 국가 수정 정보
 * @returns 수정된 국가
 * @tag countries
 *
 * @controller CountryController.updateCountry
 * @path PUT /countries/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateCountry(
  connection: IConnection,
  id: string,
  dto: updateCountry.Body,
): Promise<updateCountry.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateCountry.METADATA,
      template: updateCountry.METADATA.path,
      path: updateCountry.path(id),
    },
    dto,
  );
}
export namespace updateCountry {
  export type Body = Primitive<UpdateCountryDto>;
  export type Output = Primitive<CountryResponseDto>;

  export const METADATA = {
    method: "PUT",
    path: "/countries/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/countries/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 국가 삭제
 *
 * @param id 국가 ID
 * @tag countries
 *
 * @controller CountryController.deleteCountry
 * @path DELETE /countries/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteCountry(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteCountry.METADATA,
    template: deleteCountry.METADATA.path,
    path: deleteCountry.path(id),
  });
}
export namespace deleteCountry {
  export const METADATA = {
    method: "DELETE",
    path: "/countries/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string) =>
    `/countries/${encodeURIComponent(id?.toString() ?? "null")}`;
}
