/**
 * @packageDocumentation
 * @module api.functional.social.following
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { BooleanResponse } from "../../../../libs/social/presentation/social.controller";

/**
 * @controller SocialController.isFollowing
 * @path GET /social/following/:userId
 * @accessor api.functional.social.following.isFollowing
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function isFollowing(
  connection: IConnection,
  userId: string,
): Promise<isFollowing.Output> {
  return PlainFetcher.fetch(connection, {
    ...isFollowing.METADATA,
    template: isFollowing.METADATA.path,
    path: isFollowing.path(userId),
  });
}
export namespace isFollowing {
  export type Output = Primitive<BooleanResponse>;

  export const METADATA = {
    method: "GET",
    path: "/social/following/:userId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (userId: string) =>
    `/social/following/${encodeURIComponent(userId?.toString() ?? "null")}`;
}
