export {
  FormCardWrapper,
  FormHeader,
  FormHeaderTitle,
  BackButton,
  SubmitButton,
  TabNavigation,
  TabButton,
  FormSectionInner,
  FormRows,
  FieldRow,
  FieldLabel,
  FieldControl,
  DateFieldsRow,
  DateFieldBtn,
  FieldHint,
  Required,
  Input,
  CheckboxRow,
  BORDER_COLOR,
  FOCUS_COLOR,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TEXT_MUTED,
} from './register-form-layout.styles'
