[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = KR
ST = Seoul
L = Seoul
O = Evolution
OU = Development
CN = app.civilization.zone
emailAddress = dev@evolution.com

[v3_req]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = app.civilization.zone
DNS.2 = app.civilization.local
DNS.3 = api.civilization.zone
DNS.4 = api.civilization.local
DNS.5 = user.civilization.zone
DNS.6 = user.civilization.local
DNS.7 = localhost
DNS.8 = *.civilization.zone
DNS.9 = *.civilization.local
