/**
 * @packageDocumentation
 * @module api.functional.upload.image
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * @controller UploadController.uploadImage
 * @path POST /upload/image
 * @accessor api.functional.upload.image.uploadImage
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function uploadImage(
  connection: IConnection,
): Promise<uploadImage.Output> {
  return PlainFetcher.fetch(connection, {
    ...uploadImage.METADATA,
    template: uploadImage.METADATA.path,
    path: uploadImage.path(),
  });
}
export namespace uploadImage {
  export type Output = Primitive<{
    url: string;
    filename: string;
    originalName: string;
    size: number;
    mimetype: string;
  }>;

  export const METADATA = {
    method: "POST",
    path: "/upload/image",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/upload/image";
}
