/**
 * @packageDocumentation
 * @module api.functional.social.comment
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { CreateCommentDto } from "../../../../libs/social/presentation/social.controller";

export * as update from "./update/index";

/**
 * @controller SocialController.createComment
 * @path POST /social/comment/:curationId
 * @accessor api.functional.social.comment.createComment
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createComment(
  connection: IConnection,
  curationId: string,
  dto: createComment.Body,
): Promise<createComment.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createComment.METADATA,
      template: createComment.METADATA.path,
      path: createComment.path(curationId),
    },
    dto,
  );
}
export namespace createComment {
  export type Body = Primitive<CreateCommentDto>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "POST",
    path: "/social/comment/:curationId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (curationId: string) =>
    `/social/comment/${encodeURIComponent(curationId?.toString() ?? "null")}`;
}

/**
 * @controller SocialController.deleteComment
 * @path DELETE /social/comment/:commentId
 * @accessor api.functional.social.comment.deleteComment
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteComment(
  connection: IConnection,
  commentId: string,
): Promise<deleteComment.Output> {
  return PlainFetcher.fetch(connection, {
    ...deleteComment.METADATA,
    template: deleteComment.METADATA.path,
    path: deleteComment.path(commentId),
  });
}
export namespace deleteComment {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "DELETE",
    path: "/social/comment/:commentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (commentId: string) =>
    `/social/comment/${encodeURIComponent(commentId?.toString() ?? "null")}`;
}
