-- AlterTable
ALTER TABLE `political_party_membership` ADD COLUMN `leadership_tier` ENUM('TOP', 'SECOND', 'SENIOR', 'ORDINARY', 'JUNIOR', 'UNSPECIFIED') NULL,
    ADD COLUMN `role_category` ENUM('GENERAL_MEMBER', 'LEADERSHIP', 'PARLIAMENTARY', 'LOCAL_ORGANIZATION', 'WING_ORGAN', 'POLICY_STAFF', 'HONORARY', 'OTHER') NOT NULL DEFAULT 'OTHER';