/**
 * @packageDocumentation
 * @module api.functional.persons.detail
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * ID로 인물 상세 조회 (관계 데이터 포함)
 * @controller PersonController.getDetailById
 * @path GET /persons/:id/detail
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getDetailById(
  connection: IConnection,
  id: string,
): Promise<getDetailById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getDetailById.METADATA,
    template: getDetailById.METADATA.path,
    path: getDetailById.path(id),
  });
}
export namespace getDetailById {
  export type Output = Primitive<{
    id: string;
    name: string;
    surname: string | null;
    birthEra: any;
    birthYear: number | null;
    birthMonth: number | null;
    birthDay: number | null;
    deathEra: any;
    deathYear: number | null;
    deathMonth: number | null;
    deathDay: number | null;
    gender: string | null;
    biography: string | null;
    profileImageUrl: string | null;
    country: any;
    dynasty: any;
    religion: any;
    denomination: any;
    job: any;
    father: any;
    mother: any;
    children: any[];
    foundedCompanies: any[];
    companies: any[];
    books: any[];
    organizationRoles: any[];
    partyLeaderships: any[];
    militaryCommands: any[];
    events: any[];
    governmentPositions: any[];
    createdAt: string;
    updatedAt: string;
  }>;

  export const METADATA = {
    method: "GET",
    path: "/persons/:id/detail",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/persons/${encodeURIComponent(id?.toString() ?? "null")}/detail`;
}
