/**
 * @packageDocumentation
 * @module api.functional.persons.detail
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * ID로 인물 상세 조회 (본인 등록분만)
 * @controller PersonController.getDetailById
 * @path GET /persons/:id/detail
 * @accessor api.functional.persons.detail.getDetailById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getDetailById(
  connection: IConnection,
  id: string,
): Promise<getDetailById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getDetailById.METADATA,
    template: getDetailById.METADATA.path,
    path: getDetailById.path(id),
  });
}
export namespace getDetailById {
  export type Output = Primitive<{
    id: string;
    name: string;
    surname: string | null;
    middleName: string | null;
    nameDisplayOrder: string | null;
    originalName: string | null;
    surnameMeaning: string | null;
    nameMeaning: string | null;
    middleNameMeaning: string | null;
    nicknames: Array<{
      id: string;
      nickname: string;
      type: string | null;
      priority: number | null;
    }>;
    birthEra: any;
    birthYear: number | null;
    birthMonth: number | null;
    birthDay: number | null;
    deathEra: any;
    deathYear: number | null;
    deathMonth: number | null;
    deathDay: number | null;
    gender: string | null;
    biography: string | null;
    biographySections: Array<{
      id: string;
      title: string;
      content: string;
      order: number;
      sectionType: string | null;
    }>;
    profileImageUrl: string | null;
    regnalName: string | null;
    templeName: string | null;
    posthumousName: string | null;
    sovereignReigns: any[];
    dynastyId: string | null;
    countryId: string | null;
    fatherId: string | null;
    motherId: string | null;
    country: any;
    dynasty: any;
    religion: any;
    denomination: any;
    job: any;
    birthCityId: string | null;
    deathCityId: string | null;
    birthAdminDivisionId: string | null;
    deathAdminDivisionId: string | null;
    birthPlaceText: string | null;
    deathPlaceText: string | null;
    birthCity: { id: string; name: string } | null;
    deathCity: { id: string; name: string } | null;
    birthAdminDivision: { id: string; name: string } | null;
    deathAdminDivision: { id: string; name: string } | null;
    father: any;
    mother: any;
    children: any[];
    siblings: any[];
    foundedCompanies: any[];
    books: any[];
    organizationRoles: any[];
    partyLeaderships: any[];
    partyMemberships: any[];
    electionCandidacies: any[];
    militaryCommands: any[];
    events: any[];
    governmentPositions: any[];
    spouseRelations: any[];
    spouse: any;
    humanRelationships: any[];
    isBirthDateUnknown: boolean;
    isDeathDateUnknown: boolean;
    deathType: string | null;
    deathCause: string | null;
    deathNote: string | null;
    isAlive: boolean;
    influence: number | null;
    preEnthronementTitle: string | null;
    educations: any[];
    awards: any[];
    careers: any[];
    foundedDynasties: any[];
    countryAffiliations: any[];
    createdAt: string;
    updatedAt: string;
  }>;

  export const METADATA = {
    method: "GET",
    path: "/persons/:id/detail",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/persons/${encodeURIComponent(id?.toString() ?? "null")}/detail`;
}
