-- AlterTable
ALTER TABLE `event_country_relation` MODIFY `role` ENUM('INITIATOR', 'TARGET', 'PARTICIPANT', 'ALLY', 'ADVERSARY', 'MEDIATOR', 'OBSERVER', 'VICTIM', 'BENEFICIARY', 'FOUNDED', 'DISSOLVED', 'OTHER') NOT NULL;

