/**
 * @packageDocumentation
 * @module api.functional.persons
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreatePersonDto,
  PersonResponseDto,
  UpdatePersonDto,
} from "../../../libs/person/presentation/dto";

export * as detail from "./detail";

/**
 * 모든 인물 목록 조회
 * @controller PersonController.getAll
 * @path GET /persons
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAll(connection: IConnection): Promise<getAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAll.METADATA,
    template: getAll.METADATA.path,
    path: getAll.path(),
  });
}
export namespace getAll {
  export type Output = Primitive<PersonResponseDto[]>;

  export const METADATA = {
    method: "GET",
    path: "/persons",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/persons";
}

/**
 * ID로 인물 조회
 * @controller PersonController.getById
 * @path GET /persons/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getById(
  connection: IConnection,
  id: string,
): Promise<getById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getById.METADATA,
    template: getById.METADATA.path,
    path: getById.path(id),
  });
}
export namespace getById {
  export type Output = Primitive<PersonResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/persons/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/persons/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 인물 생성
 * @controller PersonController.create
 * @path POST /persons
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  dto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    dto,
  );
}
export namespace create {
  export type Body = Primitive<CreatePersonDto>;
  export type Output = Primitive<PersonResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/persons",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/persons";
}

/**
 * 인물 수정
 * @controller PersonController.update
 * @path PUT /persons/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  dto: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    dto,
  );
}
export namespace update {
  export type Body = Primitive<UpdatePersonDto>;
  export type Output = Primitive<PersonResponseDto>;

  export const METADATA = {
    method: "PUT",
    path: "/persons/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/persons/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 인물 삭제
 * @controller PersonController.$delete
 * @path DELETE /persons/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function $delete(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...$delete.METADATA,
    template: $delete.METADATA.path,
    path: $delete.path(id),
  });
}
export namespace $delete {
  export const METADATA = {
    method: "DELETE",
    path: "/persons/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string) =>
    `/persons/${encodeURIComponent(id?.toString() ?? "null")}`;
}
