/**
 * @packageDocumentation
 * @module api.functional.social
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as follow from "./follow";
export * as following from "./following";
export * as like from "./like";
export * as liked from "./liked";
export * as comment from "./comment";
export * as comments from "./comments";
