/**
 * @packageDocumentation
 * @module api.functional.religions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreateReligionDto,
  ReligionResponseDto,
  UpdateReligionDto,
} from "../../../libs/religion/presentation/dto";

/**
 * 모든 종교 목록 조회
 * @controller ReligionController.getAll
 * @path GET /religions
 * @accessor api.functional.religions.getAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAll(connection: IConnection): Promise<getAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAll.METADATA,
    template: getAll.METADATA.path,
    path: getAll.path(),
  });
}
export namespace getAll {
  export type Output = Primitive<Array<ReligionResponseDto>>;

  export const METADATA = {
    method: "GET",
    path: "/religions",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/religions";
}

/**
 * ID로 종교 조회
 * @controller ReligionController.getById
 * @path GET /religions/:id
 * @accessor api.functional.religions.getById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getById(
  connection: IConnection,
  id: string,
): Promise<getById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getById.METADATA,
    template: getById.METADATA.path,
    path: getById.path(id),
  });
}
export namespace getById {
  export type Output = Primitive<ReligionResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/religions/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/religions/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 종교 생성
 * @controller ReligionController.create
 * @path POST /religions
 * @accessor api.functional.religions.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  dto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    dto,
  );
}
export namespace create {
  export type Body = Primitive<CreateReligionDto>;
  export type Output = Primitive<ReligionResponseDto>;

  export const METADATA = {
    method: "POST",
    path: "/religions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/religions";
}

/**
 * 종교 수정
 * @controller ReligionController.update
 * @path PUT /religions/:id
 * @accessor api.functional.religions.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  dto: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    dto,
  );
}
export namespace update {
  export type Body = Primitive<UpdateReligionDto>;
  export type Output = Primitive<ReligionResponseDto>;

  export const METADATA = {
    method: "PUT",
    path: "/religions/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/religions/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 종교 삭제
 * @controller ReligionController._delete
 * @path DELETE /religions/:id
 * @accessor api.functional.religions._delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function _delete(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ..._delete.METADATA,
    template: _delete.METADATA.path,
    path: _delete.path(id),
  });
}
export namespace _delete {
  export const METADATA = {
    method: "DELETE",
    path: "/religions/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string) =>
    `/religions/${encodeURIComponent(id?.toString() ?? "null")}`;
}
