/**
 * @packageDocumentation
 * @module api.functional.social.follow
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * @controller SocialController.follow
 * @path POST /social/follow/:userId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function follow(
  connection: IConnection,
  userId: string,
): Promise<follow.Output> {
  return PlainFetcher.fetch(connection, {
    ...follow.METADATA,
    template: follow.METADATA.path,
    path: follow.path(userId),
  });
}
export namespace follow {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "POST",
    path: "/social/follow/:userId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (userId: string) =>
    `/social/follow/${encodeURIComponent(userId?.toString() ?? "null")}`;
}

/**
 * @controller SocialController.unfollow
 * @path DELETE /social/follow/:userId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function unfollow(
  connection: IConnection,
  userId: string,
): Promise<unfollow.Output> {
  return PlainFetcher.fetch(connection, {
    ...unfollow.METADATA,
    template: unfollow.METADATA.path,
    path: unfollow.path(userId),
  });
}
export namespace unfollow {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "DELETE",
    path: "/social/follow/:userId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (userId: string) =>
    `/social/follow/${encodeURIComponent(userId?.toString() ?? "null")}`;
}
