-- AlterTable
ALTER TABLE `government_position_tenure` MODIFY `appointment_method` ENUM('DIRECT_ELECTION', 'INDIRECT_ELECTION', 'APPOINTMENT', 'HEREDITARY', 'COUP', 'PARLIAMENTARY_ELECTION', 'CONQUEST', 'RESTORATION', 'ELECTIVE_MONARCHY', 'OTHER') NULL;

-- AlterTable
ALTER TABLE `sovereign_reign` MODIFY `appointment_method` ENUM('DIRECT_ELECTION', 'INDIRECT_ELECTION', 'APPOINTMENT', 'HEREDITARY', 'COUP', 'PARLIAMENTARY_ELECTION', 'CONQUEST', 'RESTORATION', 'ELECTIVE_MONARCHY', 'OTHER') NULL;
