/**
 * @packageDocumentation
 * @module api.functional.countries.demographic_indicators
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";

import type {
  DemographicIndicatorResponse,
  UpsertDemographicIndicatorDto,
} from "../../../../libs/country/presentation/dto";

/**
 * 국가별 인구 지표 조회
 *
 * @param id 국가 ID
 * @param query 쿼리 파라미터
 * @returns 인구 지표 목록
 * @tag countries
 *
 * @controller CountryController.getDemographicIndicators
 * @path GET /countries/:id/demographic-indicators
 * @accessor api.functional.countries.demographic_indicators.getDemographicIndicators
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getDemographicIndicators(
  connection: IConnection,
  id: string,
  query: getDemographicIndicators.Query,
): Promise<getDemographicIndicators.Output> {
  return PlainFetcher.fetch(connection, {
    ...getDemographicIndicators.METADATA,
    template: getDemographicIndicators.METADATA.path,
    path: getDemographicIndicators.path(id, query),
  });
}
export namespace getDemographicIndicators {
  export type Query = Resolved<{
    startYear?: string;
    endYear?: string;
  }>;
  export type Output = Primitive<Array<DemographicIndicatorResponse>>;

  export const METADATA = {
    method: "GET",
    path: "/countries/:id/demographic-indicators",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string, query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/countries/${encodeURIComponent(id?.toString() ?? "null")}/demographic-indicators`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * 인구 지표 생성/갱신 (countryId+year 기준 upsert)
 *
 * @tag countries
 *
 * @controller CountryController.upsertDemographicIndicator
 * @path POST /countries/:id/demographic-indicators
 * @accessor api.functional.countries.demographic_indicators.upsertDemographicIndicator
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function upsertDemographicIndicator(
  connection: IConnection,
  id: string,
  dto: upsertDemographicIndicator.Body,
): Promise<upsertDemographicIndicator.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...upsertDemographicIndicator.METADATA,
      template: upsertDemographicIndicator.METADATA.path,
      path: upsertDemographicIndicator.path(id),
    },
    dto,
  );
}
export namespace upsertDemographicIndicator {
  export type Body = Primitive<UpsertDemographicIndicatorDto>;
  export type Output = Primitive<DemographicIndicatorResponse>;

  export const METADATA = {
    method: "POST",
    path: "/countries/:id/demographic-indicators",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (id: string) =>
    `/countries/${encodeURIComponent(id?.toString() ?? "null")}/demographic-indicators`;
}

/**
 * 인구 지표 삭제 (해당 연도)
 *
 * @tag countries
 *
 * @controller CountryController.deleteDemographicIndicator
 * @path DELETE /countries/:id/demographic-indicators/:year
 * @accessor api.functional.countries.demographic_indicators.deleteDemographicIndicator
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteDemographicIndicator(
  connection: IConnection,
  id: string,
  year: number,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteDemographicIndicator.METADATA,
    template: deleteDemographicIndicator.METADATA.path,
    path: deleteDemographicIndicator.path(id, year),
  });
}
export namespace deleteDemographicIndicator {
  export const METADATA = {
    method: "DELETE",
    path: "/countries/:id/demographic-indicators/:year",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 204,
  } as const;

  export const path = (id: string, year: number) =>
    `/countries/${encodeURIComponent(id?.toString() ?? "null")}/demographic-indicators/${encodeURIComponent(year?.toString() ?? "null")}`;
}
