/**
 * @packageDocumentation
 * @module api.functional.military_units
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreateMilitaryUnitDto,
  UpdateMilitaryUnitDto,
} from "../../../libs/military/military-unit/presentation/dto";

/**
 * 모든 군부대 조회
 *
 * @tag military-units
 * @summary Get all military units
 * @returns 군부대 목록
 *
 * @controller MilitaryUnitController.getAll
 * @path GET /military-units
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAll(connection: IConnection): Promise<getAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAll.METADATA,
    template: getAll.METADATA.path,
    path: getAll.path(),
  });
}
export namespace getAll {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "GET",
    path: "/military-units",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/military-units";
}

/**
 * 특정 군부대 조회
 *
 * @param id 군부대 ID
 * @tag military-units
 * @summary Get military unit by ID
 * @returns 군부대 상세 정보
 *
 * @controller MilitaryUnitController.getById
 * @path GET /military-units/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getById(
  connection: IConnection,
  id: string,
): Promise<getById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getById.METADATA,
    template: getById.METADATA.path,
    path: getById.path(id),
  });
}
export namespace getById {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "GET",
    path: "/military-units/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/military-units/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 새로운 군부대 생성
 *
 * @param data 군부대 생성 데이터
 * @tag military-units
 * @summary Create a new military unit
 * @returns 생성된 군부대 정보
 *
 * @controller MilitaryUnitController.create
 * @path POST /military-units
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  data: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    data,
  );
}
export namespace create {
  export type Body = Primitive<CreateMilitaryUnitDto>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "POST",
    path: "/military-units",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/military-units";
}

/**
 * 군부대 정보 수정
 *
 * @param id 군부대 ID
 * @param data 수정할 데이터
 * @tag military-units
 * @summary Update military unit
 * @returns 수정된 군부대 정보
 *
 * @controller MilitaryUnitController.update
 * @path PUT /military-units/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  data: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    data,
  );
}
export namespace update {
  export type Body = Primitive<UpdateMilitaryUnitDto>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: "PUT",
    path: "/military-units/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/military-units/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * 군부대 삭제
 *
 * @param id 군부대 ID
 * @tag military-units
 * @summary Delete military unit
 *
 * @controller MilitaryUnitController.$delete
 * @path DELETE /military-units/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function $delete(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...$delete.METADATA,
    template: $delete.METADATA.path,
    path: $delete.path(id),
  });
}
export namespace $delete {
  export const METADATA = {
    method: "DELETE",
    path: "/military-units/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/military-units/${encodeURIComponent(id?.toString() ?? "null")}`;
}
